
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------



[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_AccountRoleCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Decision Maker", 0)]
	DecisionMaker = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Employee", 1)]
	Employee = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Influencer", 2)]
	Influencer = 3,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_Address1_AddressTypeCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Bill To", 0)]
	BillTo = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Other", 3)]
	Other = 4,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Primary", 2)]
	Primary = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Ship To", 1)]
	ShipTo = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_Address1_FreightTermsCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("FOB", 0)]
	FOB = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("No Charge", 1)]
	NoCharge = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_Address1_ShippingMethodCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Airborne", 0)]
	Airborne = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("DHL", 1)]
	DHL = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("FedEx", 2)]
	FedEx = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Full Load", 5)]
	FullLoad = 6,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Postal Mail", 4)]
	PostalMail = 5,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("UPS", 3)]
	UPS = 4,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Will Call", 6)]
	WillCall = 7,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_Address2_AddressTypeCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_Address2_FreightTermsCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_Address2_ShippingMethodCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_Address3_AddressTypeCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_Address3_FreightTermsCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_Address3_ShippingMethodCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_CustomerSizeCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_CustomerTypeCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_dfeta_addressverificationflag
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Customer Preferred", 2)]
	CustomerPreferred = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Failed", 1)]
	Failed = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Verified", 0)]
	Verified = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_dfeta_suppressionflag
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Deceased", 0)]
	Deceased = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Goneaway", 1)]
	Goneaway = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_EducationCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_FamilyStatusCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Divorced", 2)]
	Divorced = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Married", 1)]
	Married = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Single", 0)]
	Single = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Widowed", 3)]
	Widowed = 4,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_GenderCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Female", 1)]
	Female = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Male", 0)]
	Male = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Other", 2)]
	Other = 389040000,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_HasChildrenCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_LeadSourceCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_msdyn_orgchangestatus
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Ignore", 2, "#0000ff")]
	Ignore = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("No Feedback", 0, "#0000ff")]
	NoFeedback = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Not at Company", 1, "#0000ff")]
	NotatCompany = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_PaymentTermsCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("2% 10, Net 30", 1)]
	_210Net30 = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Net 30", 0)]
	Net30 = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Net 45", 2)]
	Net45 = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Net 60", 3)]
	Net60 = 4,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_PreferredAppointmentDayCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Friday", 5)]
	Friday = 5,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Monday", 1)]
	Monday = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Saturday", 6)]
	Saturday = 6,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Sunday", 0)]
	Sunday = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Thursday", 4)]
	Thursday = 4,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Tuesday", 2)]
	Tuesday = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Wednesday", 3)]
	Wednesday = 3,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_PreferredAppointmentTimeCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Afternoon", 1)]
	Afternoon = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Evening", 2)]
	Evening = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Morning", 0)]
	Morning = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_PreferredContactMethodCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Any", 0)]
	Any = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("E-mail", 1)]
	Email = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Home Phone", 3)]
	HomePhone = 4,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Mobile Phone", 2)]
	MobilePhone = 3,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Work Phone", 4)]
	WorkPhone = 5,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_ShippingMethodCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_StatusCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Administrative reason", 1)]
	Administrativereason = 2,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Alive", 0)]
	Alive = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Deceased", 2)]
	Deceased = 389040000,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum Contact_TerritoryCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Default Value", 0)]
	DefaultValue = 1,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_AgeRange
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("00", 0)]
	_00 = 389040029,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("01", 1)]
	_01 = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("02", 2)]
	_02 = 389040001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("03", 3)]
	_03 = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("04", 4)]
	_04 = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("05", 5)]
	_05 = 389040004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("06", 6)]
	_06 = 389040005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("07", 7)]
	_07 = 389040006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("08", 8)]
	_08 = 389040007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("09", 9)]
	_09 = 389040008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("10", 10)]
	_10 = 389040009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("11", 11)]
	_11 = 389040010,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("12", 12)]
	_12 = 389040011,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("13", 13)]
	_13 = 389040012,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("14", 14)]
	_14 = 389040013,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("15", 15)]
	_15 = 389040014,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("16", 16)]
	_16 = 389040015,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("17", 17)]
	_17 = 389040016,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("18", 18)]
	_18 = 389040017,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("19", 19)]
	_19 = 389040018,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("99", 20)]
	_99 = 389040019,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Foundation Stage", 22)]
	FoundationStage = 389040021,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Further Education", 21)]
	FurtherEducation = 389040020,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Key Stage 1", 23)]
	KeyStage1 = 389040022,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Key Stage 2", 24)]
	KeyStage2 = 389040023,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Key Stage 3", 25)]
	KeyStage3 = 389040024,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Key Stage 4", 26)]
	KeyStage4 = 389040025,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Not applicable", 27)]
	Notapplicable = 389040026,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Other", 28)]
	Other = 389040027,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Post 16", 29)]
	Post16 = 389040028,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_AppealOutcome
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Allowed", 0)]
	Allowed = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Dismissed", 1)]
	Dismissed = 389040001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Extension", 2)]
	Extension = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Extension Appeal Dismissed", 4)]
	ExtensionAppealDismissed = 389040004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Substitute Extension period", 3)]
	SubstituteExtensionperiod = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Withdrawn Appeal", 5)]
	WithdrawnAppeal = 389040005,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_classdivision
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Aegrotat (whether to honours or pass)", 7)]
	Aegrotat_whethertohonoursorpass = 389040007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Distinction", 11)]
	Distinction = 389040011,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("First class honours", 0)]
	Firstclasshonours = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Fourth class honours", 5)]
	Fourthclasshonours = 389040005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("General Degree - degree awarded after following a non-honours course/degree that " +
		"was not available to be classified", 10)]
	GeneralDegreedegreeawardedafterfollowinganonhonourscoursedegreethatwasnotavailabletobeclassified = 389040010,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Higher Degree", 16)]
	HigherDegree = 389040016,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Lower second class honours", 2)]
	Lowersecondclasshonours = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Merit", 12)]
	Merit = 389040012,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Not applicable", 14)]
	Notapplicable = 389040014,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Not Known", 15)]
	NotKnown = 389040015,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Ordinary (including divisions of ordinary, if any) degree awarded after following" +
		" a non-honours course", 9)]
	Ordinary_includingdivisionsofordinaryifanydegreeawardedafterfollowinganonhonourscourse = 389040009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Pass", 13)]
	Pass = 389040013,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Pass - degree awarded without honours following an honours course", 8)]
	Passdegreeawardedwithouthonoursfollowinganhonourscourse = 389040008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Third class honours", 4)]
	Thirdclasshonours = 389040004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Unclassified honours", 6)]
	Unclassifiedhonours = 389040006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Undivided second class honours", 3)]
	Undividedsecondclasshonours = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Upper second class honours", 1)]
	Uppersecondclasshonours = 389040001,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_CourseUnit
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Days", 0)]
	Days = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Months", 1)]
	Months = 389040001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Terms", 2)]
	Terms = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Weeks", 3)]
	Weeks = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Years", 4)]
	Years = 389040004,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_he_firstdegreeflag
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("No", 0)]
	No = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Yes", 1)]
	Yes = 389040001,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_induction_StatusCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Active", 0)]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Inactive", 1)]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_InductionExemptionReason
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Exempt", 8)]
	Exempt = 389040008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Exempt - Data Loss/Error Criteria", 9)]
	ExemptDataLossErrorCriteria = 389040009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Extended on appeal", 0)]
	Extendedonappeal = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Has, or is eligible for, full registration in Scotland", 17)]
	HasoriseligibleforfullregistrationinScotland = 389040017,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Overseas Trained Teacher", 10)]
	OverseasTrainedTeacher = 389040010,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Qualified before 07 May 1999", 11)]
	Qualifiedbefore07May1999 = 389040011,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Qualified between 07 May 1999 and 01 April 2003. First post was in Wales and last" +
		"ed a minimum of two terms.", 12)]
	Qualifiedbetween07May1999and01April2003FirstpostwasinWalesandlastedaminimumoftwoterms = 389040012,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Qualified through EEA mutual recognition route", 13)]
	QualifiedthroughEEAmutualrecognitionroute = 389040013,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Qualified through FE route between 01 Sep 2001 and 01 Sep 2004", 14)]
	QualifiedthroughFEroutebetween01Sep2001and01Sep2004 = 389040014,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Qualified through Independent route between 01 Oct 2000 and 01 Sep 2004", 15)]
	QualifiedthroughIndependentroutebetween01Oct2000and01Sep2004 = 389040015,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Registered Teacher (having at least two year\'s full time teaching experience)", 16)]
	RegisteredTeacher_havingatleasttwoyearsfulltimeteachingexperience = 389040016,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Successfully completed induction in Guernsey", 2)]
	SuccessfullycompletedinductioninGuernsey = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Successfully completed induction in Isle Of Man", 3)]
	SuccessfullycompletedinductioninIsleOfMan = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Successfully completed induction in Jersey", 4)]
	SuccessfullycompletedinductioninJersey = 389040004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Successfully completed induction in Northern Ireland", 5)]
	SuccessfullycompletedinductioninNorthernIreland = 389040005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Successfully completed induction in Service Children\'s Education schools in Germa" +
		"ny or Cyprus", 6)]
	SuccessfullycompletedinductioninServiceChildrensEducationschoolsinGermanyorCyprus = 389040006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Successfully completed induction in Wales", 7)]
	SuccessfullycompletedinductioninWales = 389040007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Successfully completed probationary period in Gibraltar", 1)]
	SuccessfullycompletedprobationaryperiodinGibraltar = 389040001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Teacher has been awarded QTLS and is exempt provided they maintain their membersh" +
		"ip with the Society for Education and Training", 18)]
	TeacherhasbeenawardedQTLSandisexemptprovidedtheymaintaintheirmembershipwiththeSocietyforEducationandTraining = 389040018,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_InductionStatus
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Exempt", 0)]
	Exempt = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Fail", 1)]
	Fail = 389040001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Failed in Wales", 8)]
	FailedinWales = 389040008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Induction Extended", 2)]
	InductionExtended = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("In Progress", 6)]
	InProgress = 389040006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Not Yet Completed", 3)]
	NotYetCompleted = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Pass", 4)]
	Pass = 389040004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Passed in Wales", 5)]
	PassedinWales = 389040005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Required to Complete", 7)]
	RequiredtoComplete = 389040007,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_initialteachertraining_StatusCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Active", 0)]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Inactive", 1)]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_ITTProgrammeType
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Apprenticeship", 19)]
	Apprenticeship = 389040019,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Assessment Only Route", 11)]
	AssessmentOnlyRoute = 389040010,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Core", 0)]
	Core = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Core Flexible", 1)]
	CoreFlexible = 389040011,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("EYITT - Assessment Only", 14, "", "EYITTAOR")]
	EYITTAssessmentOnly = 389040014,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("EYITT - Graduate Employment Based", 16, "", "EYITTGEB")]
	EYITTGraduateEmploymentBased = 389040016,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("EYITT - Graduate Entry", 15, "", "EYITTGE")]
	EYITTGraduateEntry = 389040015,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("EYITT - School Direct (Early Years)", 18, "", "EYITTSD")]
	EYITTSchoolDirect_EarlyYears = 389040018,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("EYITT - Undergraduate", 17, "", "EYITTGUR")]
	EYITTUndergraduate = 389040017,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Future Teaching Scholars", 20, "#0000ff")]
	FutureTeachingScholars = 389040020,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Graduate Teacher Programme", 10)]
	GraduateTeacherProgramme = 389040009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("HEI", 2)]
	HEI = 389040001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Licensed Teacher Programme", 12, "", "Added by helpdesk call R120680")]
	LicensedTeacherProgramme = 389040012,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Overseas Trained Teacher Programme", 8)]
	OverseasTrainedTeacherProgramme = 389040007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Registered Teacher Programme", 9)]
	RegisteredTeacherProgramme = 389040008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("School Direct training programme", 5)]
	SchoolDirecttrainingprogramme = 389040004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("School Direct training programme (Salaried)", 4)]
	SchoolDirecttrainingprogramme_Salaried = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("School Direct training programme (Self funded)", 3)]
	SchoolDirecttrainingprogramme_Selffunded = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Teach First Programme", 7)]
	TeachFirstProgramme = 389040006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Teach First Programme (CC)", 6)]
	TeachFirstProgramme_CC = 389040005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Undergraduate Opt In", 13)]
	UndergraduateOptIn = 389040013,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_ITTQualificationAim
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Academic award only", 0)]
	Academicawardonly = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Professional status and academic award", 2)]
	Professionalstatusandacademicaward = 389040001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Professional status by assessment only", 3)]
	Professionalstatusbyassessmentonly = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Professional status only", 1)]
	Professionalstatusonly = 389040000,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_ITTResult
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Application Received", 8)]
	ApplicationReceived = 389040008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Application Unsuccessful", 9)]
	ApplicationUnsuccessful = 389040009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Approved", 4)]
	Approved = 389040004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Deferred", 5)]
	Deferred = 389040005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Deferred for Skills Tests", 6)]
	DeferredforSkillsTests = 389040006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Fail", 1)]
	Fail = 389040001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Info", 10)]
	Info = 389040010,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("In Training", 3)]
	InTraining = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("No Result Submitted", 11)]
	NoResultSubmitted = 389040011,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Pass", 0)]
	Pass = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Under Assessment", 7)]
	UnderAssessment = 389040007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Withdrawn", 2)]
	Withdrawn = 389040002,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_ITTServiceLeaver
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Information refused", 3, "#0000ff")]
	Informationrefused = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Not known", 0, "#0000ff")]
	Notknown = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Trainee has left full time employment in the British Army, Royal Air Force or Roy" +
		"al Navy in the past 5 years", 2, "#0000ff")]
	TraineehasleftfulltimeemploymentintheBritishArmyRoyalAirForceorRoyalNavyinthepast5years = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Trainee has NOT LEFT full time employment in the British Army, Royal Air Force or" +
		" Royal Navy in the past 5 years", 1, "#0000ff")]
	TraineehasNOTLEFTfulltimeemploymentintheBritishArmyRoyalAirForceorRoyalNavyinthepast5years = 389040001,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_ittsubject_StatusCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Active", 0)]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Inactive", 1)]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_PersonTitle
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Baron", 0)]
	Baron = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Baroness", 1)]
	Baroness = 389040001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Canon", 2)]
	Canon = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Captain", 3)]
	Captain = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Dame", 4)]
	Dame = 389040004,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Dr.", 5)]
	Dr = 389040005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Earl", 6)]
	Earl = 389040006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Father", 7)]
	Father = 389040007,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Lady", 8)]
	Lady = 389040008,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Lord", 9)]
	Lord = 389040009,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Lt.", 10)]
	Lt = 389040010,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Major", 11)]
	Major = 389040011,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Miss", 12)]
	Miss = 389040012,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Mr.", 13)]
	Mr = 389040013,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Mrs.", 14)]
	Mrs = 389040014,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Ms.", 15)]
	Ms = 389040015,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Mx.", 16, "#0000ff")]
	Mx = 389040023,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Pastor", 17)]
	Pastor = 389040016,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Prof", 18)]
	Prof = 389040017,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Rabbi", 19)]
	Rabbi = 389040018,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Rev", 20)]
	Rev = 389040019,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Rt Hon", 21)]
	RtHon = 389040020,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Sir", 22)]
	Sir = 389040021,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Sister", 23)]
	Sister = 389040022,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_qtsregistration_StatusCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Active", 0)]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Inactive", 1)]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_qualification_dfeta_HLTA_ModerationOutcome
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("TBD", 0)]
	TBD = 389040000,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_qualification_dfeta_Type
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Higher Education", 0)]
	HigherEducation = 389040000,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("HLTA", 3)]
	HLTA = 389040003,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Mandatory Qualification", 2)]
	MandatoryQualification = 389040002,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("NPQEL", 6, "#0000ff")]
	NPQEL = 389040006,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("NPQH", 1)]
	NPQH = 389040001,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("NPQML", 4)]
	NPQML = 389040005,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("NPQSL", 5)]
	NPQSL = 389040004,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum dfeta_qualification_StatusCode
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Active", 0)]
	Active = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Inactive", 1)]
	Inactive = 2,
}

[System.Runtime.Serialization.DataContractAttribute()]
public enum appaction_ClientType
{
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Browser", 0, "#0000ff")]
	Browser = 0,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Mobile", 1, "#0000ff")]
	Mobile = 1,
	
	[System.Runtime.Serialization.EnumMemberAttribute()]
	[OptionSetMetadataAttribute("Mail App", 2, "#0000ff")]
	MailApp = 2,
}
