
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]
[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.1.0.95")]

namespace DqtApi.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ContactState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Person with whom a business unit has a relationship, such as customer, supplier, and colleague.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("contact")]
	public partial class Contact : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the contact entity
		/// </summary>
		public static class Fields
		{
			public const string BirthDate = "birthdate";
			public const string dfeta_ActiveSanctions = "dfeta_activesanctions";
			public const string dfeta_NINumber = "dfeta_ninumber";
			public const string dfeta_TRN = "dfeta_trn";
			public const string dfeta_trnrequired = "dfeta_trnrequired";
			public const string FullName = "fullname";
			public const string StateCode = "statecode";
			public const string Referencedcontact_customer_contacts = "Referencedcontact_customer_contacts";
			public const string Referencedcontact_master_contact = "Referencedcontact_master_contact";
			public const string Referencedcontact_parent_contact = "Referencedcontact_parent_contact";
			public const string dfeta_contact_dfeta_induction = "dfeta_contact_dfeta_induction";
			public const string dfeta_contact_dfeta_induction1 = "dfeta_contact_dfeta_induction1";
			public const string dfeta_contact_dfeta_initialteachertraining = "dfeta_contact_dfeta_initialteachertraining";
			public const string dfeta_contact_dfeta_initialteachertraining1 = "dfeta_contact_dfeta_initialteachertraining1";
			public const string dfeta_contact_dfeta_qtsregistration = "dfeta_contact_dfeta_qtsregistration";
			public const string dfeta_contact_dfeta_qtsregistration1 = "dfeta_contact_dfeta_qtsregistration1";
			public const string dfeta_contact_dfeta_qualification = "dfeta_contact_dfeta_qualification";
			public const string Referencingcontact_customer_contacts = "contact_customer_contacts";
			public const string Referencingcontact_master_contact = "contact_master_contact";
			public const string Referencingcontact_parent_contact = "contact_parent_contact";
			public const string dfeta_dfeta_qtsregistration_contact = "dfeta_dfeta_qtsregistration_contact";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public Contact() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntitySchemaName = "Contact";
		
		public const string PrimaryIdAttribute = "contactid";
		
		public const string PrimaryNameAttribute = "fullname";
		
		public const string EntityLogicalName = "contact";
		
		public const string EntityLogicalCollectionName = "contacts";
		
		public const string EntitySetName = "contacts";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Birth date of the contact.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("birthdate")]
		public System.Nullable<System.DateTime> BirthDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("birthdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BirthDate");
				this.SetAttributeValue("birthdate", value);
				this.OnPropertyChanged("BirthDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_activesanctions")]
		public System.Nullable<bool> dfeta_ActiveSanctions
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfeta_activesanctions");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_ActiveSanctions");
				this.SetAttributeValue("dfeta_activesanctions", value);
				this.OnPropertyChanged("dfeta_ActiveSanctions");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_ninumber")]
		public string dfeta_NINumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfeta_ninumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_NINumber");
				this.SetAttributeValue("dfeta_ninumber", value);
				this.OnPropertyChanged("dfeta_NINumber");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_trn")]
		public string dfeta_TRN
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfeta_trn");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_TRN");
				this.SetAttributeValue("dfeta_trn", value);
				this.OnPropertyChanged("dfeta_TRN");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_trnrequired")]
		public System.Nullable<bool> dfeta_trnrequired
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfeta_trnrequired");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_trnrequired");
				this.SetAttributeValue("dfeta_trnrequired", value);
				this.OnPropertyChanged("dfeta_trnrequired");
			}
		}
		
		/// <summary>
		/// Full name of the contact.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("fullname")]
		public string FullName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("fullname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("FullName");
				this.SetAttributeValue("fullname", value);
				this.OnPropertyChanged("FullName");
			}
		}
		
		/// <summary>
		/// Status of the contact.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<DqtApi.Models.ContactState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((DqtApi.Models.ContactState)(System.Enum.ToObject(typeof(DqtApi.Models.ContactState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// 1:N contact_customer_contacts
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contact_customer_contacts", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.Contact> Referencedcontact_customer_contacts
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.Contact>("contact_customer_contacts", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencedcontact_customer_contacts");
				this.SetRelatedEntities<DqtApi.Models.Contact>("contact_customer_contacts", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedcontact_customer_contacts");
			}
		}
		
		/// <summary>
		/// 1:N contact_master_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contact_master_contact", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.Contact> Referencedcontact_master_contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.Contact>("contact_master_contact", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencedcontact_master_contact");
				this.SetRelatedEntities<DqtApi.Models.Contact>("contact_master_contact", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedcontact_master_contact");
			}
		}
		
		/// <summary>
		/// 1:N contact_parent_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contact_parent_contact", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.Contact> Referencedcontact_parent_contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.Contact>("contact_parent_contact", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencedcontact_parent_contact");
				this.SetRelatedEntities<DqtApi.Models.Contact>("contact_parent_contact", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedcontact_parent_contact");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_contact_dfeta_induction
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_induction")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_induction> dfeta_contact_dfeta_induction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_induction>("dfeta_contact_dfeta_induction", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_induction");
				this.SetRelatedEntities<DqtApi.Models.dfeta_induction>("dfeta_contact_dfeta_induction", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_induction");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_contact_dfeta_induction1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_induction1")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_induction> dfeta_contact_dfeta_induction1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_induction>("dfeta_contact_dfeta_induction1", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_induction1");
				this.SetRelatedEntities<DqtApi.Models.dfeta_induction>("dfeta_contact_dfeta_induction1", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_induction1");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_contact_dfeta_initialteachertraining
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_initialteachertraining")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_initialteachertraining> dfeta_contact_dfeta_initialteachertraining
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_initialteachertraining>("dfeta_contact_dfeta_initialteachertraining", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_initialteachertraining");
				this.SetRelatedEntities<DqtApi.Models.dfeta_initialteachertraining>("dfeta_contact_dfeta_initialteachertraining", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_initialteachertraining");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_contact_dfeta_initialteachertraining1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_initialteachertraining1")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_initialteachertraining> dfeta_contact_dfeta_initialteachertraining1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_initialteachertraining>("dfeta_contact_dfeta_initialteachertraining1", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_initialteachertraining1");
				this.SetRelatedEntities<DqtApi.Models.dfeta_initialteachertraining>("dfeta_contact_dfeta_initialteachertraining1", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_initialteachertraining1");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_contact_dfeta_qtsregistration
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_qtsregistration")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_qtsregistration> dfeta_contact_dfeta_qtsregistration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_qtsregistration>("dfeta_contact_dfeta_qtsregistration", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_qtsregistration");
				this.SetRelatedEntities<DqtApi.Models.dfeta_qtsregistration>("dfeta_contact_dfeta_qtsregistration", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_qtsregistration");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_contact_dfeta_qtsregistration1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_qtsregistration1")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_qtsregistration> dfeta_contact_dfeta_qtsregistration1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_qtsregistration>("dfeta_contact_dfeta_qtsregistration1", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_qtsregistration1");
				this.SetRelatedEntities<DqtApi.Models.dfeta_qtsregistration>("dfeta_contact_dfeta_qtsregistration1", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_qtsregistration1");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_contact_dfeta_qualification
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_qualification")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_qualification> dfeta_contact_dfeta_qualification
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_qualification>("dfeta_contact_dfeta_qualification", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_qualification");
				this.SetRelatedEntities<DqtApi.Models.dfeta_qualification>("dfeta_contact_dfeta_qualification", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_qualification");
			}
		}
		
		/// <summary>
		/// N:1 contact_customer_contacts
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentcustomerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contact_customer_contacts", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public DqtApi.Models.Contact Referencingcontact_customer_contacts
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.Contact>("contact_customer_contacts", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencingcontact_customer_contacts");
				this.SetRelatedEntity<DqtApi.Models.Contact>("contact_customer_contacts", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingcontact_customer_contacts");
			}
		}
		
		/// <summary>
		/// N:1 contact_master_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("masterid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contact_master_contact", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public DqtApi.Models.Contact Referencingcontact_master_contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.Contact>("contact_master_contact", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencingcontact_master_contact");
				this.SetRelatedEntity<DqtApi.Models.Contact>("contact_master_contact", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingcontact_master_contact");
			}
		}
		
		/// <summary>
		/// N:1 contact_parent_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parent_contactid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("contact_parent_contact", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public DqtApi.Models.Contact Referencingcontact_parent_contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.Contact>("contact_parent_contact", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencingcontact_parent_contact");
				this.SetRelatedEntity<DqtApi.Models.Contact>("contact_parent_contact", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingcontact_parent_contact");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_dfeta_qtsregistration_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_qtsregistrationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_dfeta_qtsregistration_contact")]
		public DqtApi.Models.dfeta_qtsregistration dfeta_dfeta_qtsregistration_contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.dfeta_qtsregistration>("dfeta_dfeta_qtsregistration_contact", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_dfeta_qtsregistration_contact");
				this.SetRelatedEntity<DqtApi.Models.dfeta_qtsregistration>("dfeta_dfeta_qtsregistration_contact", null, value);
				this.OnPropertyChanged("dfeta_dfeta_qtsregistration_contact");
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum dfeta_inductionState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dfeta_induction")]
	public partial class dfeta_induction : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the dfeta_induction entity
		/// </summary>
		public static class Fields
		{
			public const string dfeta_CompletionDate = "dfeta_completiondate";
			public const string dfeta_InductionStatus = "dfeta_inductionstatus";
			public const string dfeta_PersonId = "dfeta_personid";
			public const string dfeta_StartDate = "dfeta_startdate";
			public const string StateCode = "statecode";
			public const string dfeta_dfeta_induction_dfeta_qtsregistration = "dfeta_dfeta_induction_dfeta_qtsregistration";
			public const string dfeta_contact_dfeta_induction = "dfeta_contact_dfeta_induction";
			public const string dfeta_contact_dfeta_induction1 = "dfeta_contact_dfeta_induction1";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dfeta_induction() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntitySchemaName = "dfeta_induction";
		
		public const string PrimaryIdAttribute = "dfeta_inductionid";
		
		public const string PrimaryNameAttribute = "dfeta_name";
		
		public const string EntityLogicalName = "dfeta_induction";
		
		public const string EntityLogicalCollectionName = "dfeta_inductions";
		
		public const string EntitySetName = "dfeta_inductions";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_completiondate")]
		public System.Nullable<System.DateTime> dfeta_CompletionDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfeta_completiondate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_CompletionDate");
				this.SetAttributeValue("dfeta_completiondate", value);
				this.OnPropertyChanged("dfeta_CompletionDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_inductionstatus")]
		public virtual dfeta_InductionStatus? dfeta_InductionStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((dfeta_InductionStatus?)(EntityOptionSetEnum.GetEnum(this, "dfeta_inductionstatus")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_InductionStatus");
				this.SetAttributeValue("dfeta_inductionstatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("dfeta_InductionStatus");
			}
		}
		
		/// <summary>
		/// Unique identifier for Person associated with Induction.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_personid")]
		public Microsoft.Xrm.Sdk.EntityReference dfeta_PersonId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfeta_personid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_PersonId");
				this.SetAttributeValue("dfeta_personid", value);
				this.OnPropertyChanged("dfeta_PersonId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_startdate")]
		public System.Nullable<System.DateTime> dfeta_StartDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfeta_startdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_StartDate");
				this.SetAttributeValue("dfeta_startdate", value);
				this.OnPropertyChanged("dfeta_StartDate");
			}
		}
		
		/// <summary>
		/// Status of the Induction
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<DqtApi.Models.dfeta_inductionState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((DqtApi.Models.dfeta_inductionState)(System.Enum.ToObject(typeof(DqtApi.Models.dfeta_inductionState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_dfeta_induction_dfeta_qtsregistration
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_dfeta_induction_dfeta_qtsregistration")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_qtsregistration> dfeta_dfeta_induction_dfeta_qtsregistration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_qtsregistration>("dfeta_dfeta_induction_dfeta_qtsregistration", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_dfeta_induction_dfeta_qtsregistration");
				this.SetRelatedEntities<DqtApi.Models.dfeta_qtsregistration>("dfeta_dfeta_induction_dfeta_qtsregistration", null, value);
				this.OnPropertyChanged("dfeta_dfeta_induction_dfeta_qtsregistration");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_contact_dfeta_induction
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_personid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_induction")]
		public DqtApi.Models.Contact dfeta_contact_dfeta_induction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_induction", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_induction");
				this.SetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_induction", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_induction");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_contact_dfeta_induction1
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_requestedbyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_induction1")]
		public DqtApi.Models.Contact dfeta_contact_dfeta_induction1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_induction1", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_induction1");
				this.SetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_induction1", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_induction1");
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum dfeta_initialteachertrainingState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dfeta_initialteachertraining")]
	public partial class dfeta_initialteachertraining : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the dfeta_initialteachertraining entity
		/// </summary>
		public static class Fields
		{
			public const string dfeta_ITTQualificationId = "dfeta_ittqualificationid";
			public const string dfeta_PersonId = "dfeta_personid";
			public const string dfeta_ProgrammeEndDate = "dfeta_programmeenddate";
			public const string dfeta_ProgrammeStartDate = "dfeta_programmestartdate";
			public const string dfeta_ProgrammeType = "dfeta_programmetype";
			public const string dfeta_Result = "dfeta_result";
			public const string dfeta_Subject1Id = "dfeta_subject1id";
			public const string dfeta_Subject2Id = "dfeta_subject2id";
			public const string dfeta_Subject3Id = "dfeta_subject3id";
			public const string StateCode = "statecode";
			public const string dfeta_contact_dfeta_initialteachertraining = "dfeta_contact_dfeta_initialteachertraining";
			public const string dfeta_contact_dfeta_initialteachertraining1 = "dfeta_contact_dfeta_initialteachertraining1";
			public const string dfeta_dfeta_ittsubject1_dfeta_initialteachertra = "dfeta_dfeta_ittsubject1_dfeta_initialteachertra";
			public const string dfeta_dfeta_ittsubject2_dfeta_initialteachertra = "dfeta_dfeta_ittsubject2_dfeta_initialteachertra";
			public const string dfeta_dfeta_ittsubject3_dfeta_initialteachertra = "dfeta_dfeta_ittsubject3_dfeta_initialteachertra";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dfeta_initialteachertraining() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntitySchemaName = "dfeta_initialteachertraining";
		
		public const string PrimaryIdAttribute = "dfeta_initialteachertrainingid";
		
		public const string PrimaryNameAttribute = "dfeta_name";
		
		public const string EntityLogicalName = "dfeta_initialteachertraining";
		
		public const string EntityLogicalCollectionName = "dfeta_initialteachertrainings";
		
		public const string EntitySetName = "dfeta_initialteachertrainings";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier for Qualification - ITT associated with Initial Teacher Training.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_ittqualificationid")]
		public Microsoft.Xrm.Sdk.EntityReference dfeta_ITTQualificationId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfeta_ittqualificationid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_ITTQualificationId");
				this.SetAttributeValue("dfeta_ittqualificationid", value);
				this.OnPropertyChanged("dfeta_ITTQualificationId");
			}
		}
		
		/// <summary>
		/// Unique identifier for Person associated with Initial Teacher Training.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_personid")]
		public Microsoft.Xrm.Sdk.EntityReference dfeta_PersonId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfeta_personid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_PersonId");
				this.SetAttributeValue("dfeta_personid", value);
				this.OnPropertyChanged("dfeta_PersonId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_programmeenddate")]
		public System.Nullable<System.DateTime> dfeta_ProgrammeEndDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfeta_programmeenddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_ProgrammeEndDate");
				this.SetAttributeValue("dfeta_programmeenddate", value);
				this.OnPropertyChanged("dfeta_ProgrammeEndDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_programmestartdate")]
		public System.Nullable<System.DateTime> dfeta_ProgrammeStartDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfeta_programmestartdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_ProgrammeStartDate");
				this.SetAttributeValue("dfeta_programmestartdate", value);
				this.OnPropertyChanged("dfeta_ProgrammeStartDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_programmetype")]
		public virtual dfeta_ITTProgrammeType? dfeta_ProgrammeType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((dfeta_ITTProgrammeType?)(EntityOptionSetEnum.GetEnum(this, "dfeta_programmetype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_ProgrammeType");
				this.SetAttributeValue("dfeta_programmetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("dfeta_ProgrammeType");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_result")]
		public virtual dfeta_ITTResult? dfeta_Result
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((dfeta_ITTResult?)(EntityOptionSetEnum.GetEnum(this, "dfeta_result")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_Result");
				this.SetAttributeValue("dfeta_result", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("dfeta_Result");
			}
		}
		
		/// <summary>
		/// Unique identifier for Subject - ITT associated with Initial Teacher Training.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_subject1id")]
		public Microsoft.Xrm.Sdk.EntityReference dfeta_Subject1Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfeta_subject1id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_Subject1Id");
				this.SetAttributeValue("dfeta_subject1id", value);
				this.OnPropertyChanged("dfeta_Subject1Id");
			}
		}
		
		/// <summary>
		/// Unique identifier for Subject - ITT associated with Initial Teacher Training.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_subject2id")]
		public Microsoft.Xrm.Sdk.EntityReference dfeta_Subject2Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfeta_subject2id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_Subject2Id");
				this.SetAttributeValue("dfeta_subject2id", value);
				this.OnPropertyChanged("dfeta_Subject2Id");
			}
		}
		
		/// <summary>
		/// Unique identifier for Subject - ITT associated with Initial Teacher Training.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_subject3id")]
		public Microsoft.Xrm.Sdk.EntityReference dfeta_Subject3Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfeta_subject3id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_Subject3Id");
				this.SetAttributeValue("dfeta_subject3id", value);
				this.OnPropertyChanged("dfeta_Subject3Id");
			}
		}
		
		/// <summary>
		/// Status of the Initial Teacher Training
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<DqtApi.Models.dfeta_initialteachertrainingState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((DqtApi.Models.dfeta_initialteachertrainingState)(System.Enum.ToObject(typeof(DqtApi.Models.dfeta_initialteachertrainingState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_contact_dfeta_initialteachertraining
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_personid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_initialteachertraining")]
		public DqtApi.Models.Contact dfeta_contact_dfeta_initialteachertraining
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_initialteachertraining", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_initialteachertraining");
				this.SetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_initialteachertraining", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_initialteachertraining");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_contact_dfeta_initialteachertraining1
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_requestedbyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_initialteachertraining1")]
		public DqtApi.Models.Contact dfeta_contact_dfeta_initialteachertraining1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_initialteachertraining1", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_initialteachertraining1");
				this.SetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_initialteachertraining1", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_initialteachertraining1");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_dfeta_ittsubject1_dfeta_initialteachertra
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_subject1id")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_dfeta_ittsubject1_dfeta_initialteachertra")]
		public DqtApi.Models.dfeta_ittsubject dfeta_dfeta_ittsubject1_dfeta_initialteachertra
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.dfeta_ittsubject>("dfeta_dfeta_ittsubject1_dfeta_initialteachertra", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_dfeta_ittsubject1_dfeta_initialteachertra");
				this.SetRelatedEntity<DqtApi.Models.dfeta_ittsubject>("dfeta_dfeta_ittsubject1_dfeta_initialteachertra", null, value);
				this.OnPropertyChanged("dfeta_dfeta_ittsubject1_dfeta_initialteachertra");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_dfeta_ittsubject2_dfeta_initialteachertra
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_subject2id")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_dfeta_ittsubject2_dfeta_initialteachertra")]
		public DqtApi.Models.dfeta_ittsubject dfeta_dfeta_ittsubject2_dfeta_initialteachertra
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.dfeta_ittsubject>("dfeta_dfeta_ittsubject2_dfeta_initialteachertra", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_dfeta_ittsubject2_dfeta_initialteachertra");
				this.SetRelatedEntity<DqtApi.Models.dfeta_ittsubject>("dfeta_dfeta_ittsubject2_dfeta_initialteachertra", null, value);
				this.OnPropertyChanged("dfeta_dfeta_ittsubject2_dfeta_initialteachertra");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_dfeta_ittsubject3_dfeta_initialteachertra
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_subject3id")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_dfeta_ittsubject3_dfeta_initialteachertra")]
		public DqtApi.Models.dfeta_ittsubject dfeta_dfeta_ittsubject3_dfeta_initialteachertra
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.dfeta_ittsubject>("dfeta_dfeta_ittsubject3_dfeta_initialteachertra", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_dfeta_ittsubject3_dfeta_initialteachertra");
				this.SetRelatedEntity<DqtApi.Models.dfeta_ittsubject>("dfeta_dfeta_ittsubject3_dfeta_initialteachertra", null, value);
				this.OnPropertyChanged("dfeta_dfeta_ittsubject3_dfeta_initialteachertra");
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum dfeta_ittsubjectState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dfeta_ittsubject")]
	public partial class dfeta_ittsubject : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the dfeta_ittsubject entity
		/// </summary>
		public static class Fields
		{
			public const string dfeta_Value = "dfeta_value";
			public const string StateCode = "statecode";
			public const string dfeta_dfeta_ittsubject1_dfeta_initialteachertra = "dfeta_dfeta_ittsubject1_dfeta_initialteachertra";
			public const string dfeta_dfeta_ittsubject2_dfeta_initialteachertra = "dfeta_dfeta_ittsubject2_dfeta_initialteachertra";
			public const string dfeta_dfeta_ittsubject3_dfeta_initialteachertra = "dfeta_dfeta_ittsubject3_dfeta_initialteachertra";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dfeta_ittsubject() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntitySchemaName = "dfeta_ittsubject";
		
		public const string PrimaryIdAttribute = "dfeta_ittsubjectid";
		
		public const string PrimaryNameAttribute = "dfeta_name";
		
		public const string EntityLogicalName = "dfeta_ittsubject";
		
		public const string EntityLogicalCollectionName = "dfeta_ittsubjects";
		
		public const string EntitySetName = "dfeta_ittsubjects";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_value")]
		public string dfeta_Value
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfeta_value");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_Value");
				this.SetAttributeValue("dfeta_value", value);
				this.OnPropertyChanged("dfeta_Value");
			}
		}
		
		/// <summary>
		/// Status of the ITT Subject
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<DqtApi.Models.dfeta_ittsubjectState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((DqtApi.Models.dfeta_ittsubjectState)(System.Enum.ToObject(typeof(DqtApi.Models.dfeta_ittsubjectState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_dfeta_ittsubject1_dfeta_initialteachertra
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_dfeta_ittsubject1_dfeta_initialteachertra")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_initialteachertraining> dfeta_dfeta_ittsubject1_dfeta_initialteachertra
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_initialteachertraining>("dfeta_dfeta_ittsubject1_dfeta_initialteachertra", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_dfeta_ittsubject1_dfeta_initialteachertra");
				this.SetRelatedEntities<DqtApi.Models.dfeta_initialteachertraining>("dfeta_dfeta_ittsubject1_dfeta_initialteachertra", null, value);
				this.OnPropertyChanged("dfeta_dfeta_ittsubject1_dfeta_initialteachertra");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_dfeta_ittsubject2_dfeta_initialteachertra
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_dfeta_ittsubject2_dfeta_initialteachertra")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_initialteachertraining> dfeta_dfeta_ittsubject2_dfeta_initialteachertra
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_initialteachertraining>("dfeta_dfeta_ittsubject2_dfeta_initialteachertra", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_dfeta_ittsubject2_dfeta_initialteachertra");
				this.SetRelatedEntities<DqtApi.Models.dfeta_initialteachertraining>("dfeta_dfeta_ittsubject2_dfeta_initialteachertra", null, value);
				this.OnPropertyChanged("dfeta_dfeta_ittsubject2_dfeta_initialteachertra");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_dfeta_ittsubject3_dfeta_initialteachertra
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_dfeta_ittsubject3_dfeta_initialteachertra")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.dfeta_initialteachertraining> dfeta_dfeta_ittsubject3_dfeta_initialteachertra
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.dfeta_initialteachertraining>("dfeta_dfeta_ittsubject3_dfeta_initialteachertra", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_dfeta_ittsubject3_dfeta_initialteachertra");
				this.SetRelatedEntities<DqtApi.Models.dfeta_initialteachertraining>("dfeta_dfeta_ittsubject3_dfeta_initialteachertra", null, value);
				this.OnPropertyChanged("dfeta_dfeta_ittsubject3_dfeta_initialteachertra");
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum dfeta_qtsregistrationState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dfeta_qtsregistration")]
	public partial class dfeta_qtsregistration : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the dfeta_qtsregistration entity
		/// </summary>
		public static class Fields
		{
			public const string dfeta_name = "dfeta_name";
			public const string dfeta_PersonId = "dfeta_personid";
			public const string dfeta_QTSDate = "dfeta_qtsdate";
			public const string StateCode = "statecode";
			public const string dfeta_dfeta_qtsregistration_contact = "dfeta_dfeta_qtsregistration_contact";
			public const string dfeta_contact_dfeta_qtsregistration = "dfeta_contact_dfeta_qtsregistration";
			public const string dfeta_contact_dfeta_qtsregistration1 = "dfeta_contact_dfeta_qtsregistration1";
			public const string dfeta_dfeta_induction_dfeta_qtsregistration = "dfeta_dfeta_induction_dfeta_qtsregistration";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dfeta_qtsregistration() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntitySchemaName = "dfeta_qtsregistration";
		
		public const string PrimaryIdAttribute = "dfeta_qtsregistrationid";
		
		public const string PrimaryNameAttribute = "dfeta_name";
		
		public const string EntityLogicalName = "dfeta_qtsregistration";
		
		public const string EntityLogicalCollectionName = "dfeta_qtsregistrations";
		
		public const string EntitySetName = "dfeta_qtsregistrations";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_name")]
		public string dfeta_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfeta_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_name");
				this.SetAttributeValue("dfeta_name", value);
				this.OnPropertyChanged("dfeta_name");
			}
		}
		
		/// <summary>
		/// Unique identifier for Person associated with QTS Registration.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_personid")]
		public Microsoft.Xrm.Sdk.EntityReference dfeta_PersonId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfeta_personid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_PersonId");
				this.SetAttributeValue("dfeta_personid", value);
				this.OnPropertyChanged("dfeta_PersonId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_qtsdate")]
		public System.Nullable<System.DateTime> dfeta_QTSDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfeta_qtsdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_QTSDate");
				this.SetAttributeValue("dfeta_qtsdate", value);
				this.OnPropertyChanged("dfeta_QTSDate");
			}
		}
		
		/// <summary>
		/// Status of the QTS Registration
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<DqtApi.Models.dfeta_qtsregistrationState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((DqtApi.Models.dfeta_qtsregistrationState)(System.Enum.ToObject(typeof(DqtApi.Models.dfeta_qtsregistrationState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// 1:N dfeta_dfeta_qtsregistration_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_dfeta_qtsregistration_contact")]
		public System.Collections.Generic.IEnumerable<DqtApi.Models.Contact> dfeta_dfeta_qtsregistration_contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<DqtApi.Models.Contact>("dfeta_dfeta_qtsregistration_contact", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_dfeta_qtsregistration_contact");
				this.SetRelatedEntities<DqtApi.Models.Contact>("dfeta_dfeta_qtsregistration_contact", null, value);
				this.OnPropertyChanged("dfeta_dfeta_qtsregistration_contact");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_contact_dfeta_qtsregistration
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_personid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_qtsregistration")]
		public DqtApi.Models.Contact dfeta_contact_dfeta_qtsregistration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_qtsregistration", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_qtsregistration");
				this.SetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_qtsregistration", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_qtsregistration");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_contact_dfeta_qtsregistration1
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_requestedbyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_qtsregistration1")]
		public DqtApi.Models.Contact dfeta_contact_dfeta_qtsregistration1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_qtsregistration1", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_qtsregistration1");
				this.SetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_qtsregistration1", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_qtsregistration1");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_dfeta_induction_dfeta_qtsregistration
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_inductionid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_dfeta_induction_dfeta_qtsregistration")]
		public DqtApi.Models.dfeta_induction dfeta_dfeta_induction_dfeta_qtsregistration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.dfeta_induction>("dfeta_dfeta_induction_dfeta_qtsregistration", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_dfeta_induction_dfeta_qtsregistration");
				this.SetRelatedEntity<DqtApi.Models.dfeta_induction>("dfeta_dfeta_induction_dfeta_qtsregistration", null, value);
				this.OnPropertyChanged("dfeta_dfeta_induction_dfeta_qtsregistration");
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum dfeta_qualificationState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dfeta_qualification")]
	public partial class dfeta_qualification : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the dfeta_qualification entity
		/// </summary>
		public static class Fields
		{
			public const string dfeta_CompletionorAwardDate = "dfeta_completionorawarddate";
			public const string dfeta_PersonId = "dfeta_personid";
			public const string dfeta_Type = "dfeta_type";
			public const string dfeta_contact_dfeta_qualification = "dfeta_contact_dfeta_qualification";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dfeta_qualification() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntitySchemaName = "dfeta_qualification";
		
		public const string PrimaryIdAttribute = "dfeta_qualificationid";
		
		public const string PrimaryNameAttribute = "dfeta_name";
		
		public const string EntityLogicalName = "dfeta_qualification";
		
		public const string EntityLogicalCollectionName = "dfeta_qualifications";
		
		public const string EntitySetName = "dfeta_qualifications";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_completionorawarddate")]
		public System.Nullable<System.DateTime> dfeta_CompletionorAwardDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfeta_completionorawarddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_CompletionorAwardDate");
				this.SetAttributeValue("dfeta_completionorawarddate", value);
				this.OnPropertyChanged("dfeta_CompletionorAwardDate");
			}
		}
		
		/// <summary>
		/// Unique identifier for Person associated with Qualification.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_personid")]
		public Microsoft.Xrm.Sdk.EntityReference dfeta_PersonId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfeta_personid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_PersonId");
				this.SetAttributeValue("dfeta_personid", value);
				this.OnPropertyChanged("dfeta_PersonId");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_type")]
		public virtual dfeta_qualification_dfeta_Type? dfeta_Type
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((dfeta_qualification_dfeta_Type?)(EntityOptionSetEnum.GetEnum(this, "dfeta_type")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_Type");
				this.SetAttributeValue("dfeta_type", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("dfeta_Type");
			}
		}
		
		/// <summary>
		/// N:1 dfeta_contact_dfeta_qualification
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfeta_personid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfeta_contact_dfeta_qualification")]
		public DqtApi.Models.Contact dfeta_contact_dfeta_qualification
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_qualification", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dfeta_contact_dfeta_qualification");
				this.SetRelatedEntity<DqtApi.Models.Contact>("dfeta_contact_dfeta_qualification", null, value);
				this.OnPropertyChanged("dfeta_contact_dfeta_qualification");
			}
		}
	}
	
	internal sealed class EntityOptionSetEnum
	{
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public static System.Nullable<int> GetEnum(Microsoft.Xrm.Sdk.Entity entity, string attributeLogicalName)
		{
			if (entity.Attributes.ContainsKey(attributeLogicalName))
			{
				Microsoft.Xrm.Sdk.OptionSetValue value = entity.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>(attributeLogicalName);
				if (value != null)
				{
					return value.Value;
				}
			}
			return null;
		}
	}
	
	/// <summary>
	/// Attribute to handle storing the OptionSet's Metadata.
	/// </summary>
	[System.AttributeUsageAttribute(System.AttributeTargets.Field)]
	public sealed class OptionSetMetadataAttribute : System.Attribute
	{
		
		/// <summary>
		/// Color of the OptionSetValue.
		/// </summary>
		public string Color { get; set; }
		
		/// <summary>
		/// Description of the OptionSetValue.
		/// </summary>
		public string Description { get; set; }
		
		/// <summary>
		/// Display order index of the OptionSetValue.
		/// </summary>
		public int DisplayIndex { get; set; }
		
		/// <summary>
		/// External value of the OptionSetValue.
		/// </summary>
		public string ExternalValue { get; set; }
		
		/// <summary>
		/// Name of the OptionSetValue.
		/// </summary>
		public string Name { get; set; }
		
		/// <summary>
		/// Initializes a new instance of the <see cref="OptionSetMetadataAttribute"/> class.
		/// </summary>
		/// <param name="name">Name of the value.</param>
		/// <param name="displayIndex">Display order index of the value.</param>
		/// <param name="color">Color of the value.</param>
		/// <param name="description">Description of the value.</param>
		/// <param name="externalValue">External value of the value.</param>
		[System.Diagnostics.DebuggerNonUserCode()]
		public OptionSetMetadataAttribute(string name, int displayIndex, string color = null, string description = null, string externalValue = null)
		{
			this.Color = color;
			this.Description = description;
			this.ExternalValue = externalValue;
			this.DisplayIndex = displayIndex;
			this.Name = name;
		}
	}
	
	/// <summary>
	/// Extension class to handle retrieving of OptionSetMetadataAttribute.
	/// </summary>
	public static class OptionSetExtension
	{
		
		/// <summary>
		/// Returns the OptionSetMetadataAttribute for the given enum value
		/// </summary>
		/// <typeparam name="T">OptionSet Enum Type</typeparam>
		/// <param name="value">Enum Value with OptionSetMetadataAttribute</param>
		[System.Diagnostics.DebuggerNonUserCode()]
		public static OptionSetMetadataAttribute GetMetadata<T>(this T value)
			where T :  struct, System.IConvertible
		{
			System.Type enumType = typeof(T);
			if (!enumType.IsEnum)
			{
				throw new System.ArgumentException("T must be an enum!");
			}
			System.Reflection.MemberInfo[] members = enumType.GetMember(value.ToString());
			for (int i = 0; (i < members.Length); i++
			)
			{
				System.Attribute attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(members[i], typeof(OptionSetMetadataAttribute));
				if (attribute != null)
				{
					return ((OptionSetMetadataAttribute)(attribute));
				}
			}
			throw new System.ArgumentException("T must be an enum adorned with an OptionSetMetadataAttribute!");
		}
	}
}
