CREATE TABLE trs_route_migration_report_items
(
    route_migration_report_item_id uniqueidentifier NOT NULL PRIMARY KEY,
    person_id uniqueidentifier NOT NULL,
    [migrated] bit,
    not_migrated_reason varchar(100),
    not_migrated_reason varchar(100),
    dqt_initial_teacher_training_id uniqueidentifier,
    dqt_itt_slug_id varchar(150),
    dqt_itt_programme_type varchar(100),
    dqt_itt_programme_start_date date,
    dqt_itt_programme_end_date date,
    dqt_itt_result varchar(50),
    dqt_itt_qualification_name varchar(250),
    dqt_itt_qualification_value varchar(20),
    dqt_itt_provider_id uniqueidentifier,
    dqt_itt_provider_name varchar(250),
    dqt_itt_provider_ukprn varchar(20),    
    dqt_itt_country_name varchar(250),
    dqt_itt_country_value varchar(20),
    dqt_itt_subject1_name varchar(250),
    dqt_itt_subject1_value varchar(20),
    dqt_itt_subject2_name varchar(250),
    dqt_itt_subject2_value varchar(20),
    dqt_itt_subject3_name varchar(250),
    dqt_itt_subject3_value varchar(20),
    dqt_age_range_from varchar(20),
    dqt_age_range_to varchar(20),
    dqt_qts_registration_id uniqueidentifier,
    dqt_teacher_status_name varchar(450),
    dqt_teacher_status_value varchar(20),
    dqt_early_years_status_name varchar(450),
    dqt_early_years_status_value varchar(20),
    dqt_qts_date date,
    dqt_eyts_date date,
    dqt_partial_recognition_date date,
    dqt_qtls_date date,
    dqt_qtls_has_been_set bit,
    status_derived_route_to_professional_status_type_id uniqueidentifier,
    status_derived_route_to_professional_status_type_name varchar(100),
    programme_type_derived_route_to_professional_status_type_id uniqueidentifier,
    programme_type_derived_route_to_professional_status_type_name varchar(100),
    itt_qualification_derived_route_to_professional_status_type_id uniqueidentifier,
    itt_qualification_derived_route_to_professional_status_type_name varchar(100),
    multiple_potential_compatible_itt_records text,
    induction_exemption_reason_ids_moved_from_person text,
    contact_itt_row_count int,
    contact_qts_row_count int,
    route_to_professional_status_type_id uniqueidentifier,
    route_to_professional_status_type_name varchar(100),
    source_application_reference varchar(200),
    source_application_user_id uniqueidentifier,
    source_application_user_short_name varchar(25),
    [status] varchar(20),
    holds_from date,
    training_start_date date,
    training_end_date date,
    training_subject1_name varchar(200),
    training_subject1_reference varchar(10),
    training_subject2_name varchar(200),
    training_subject2_reference varchar(10),
    training_subject3_name varchar(200),
    training_subject3_reference varchar(10),
    training_age_specialism_type varchar(20),
    training_age_specialism_range_from int,
    training_age_specialism_range_to int,
    training_country_name varchar(200),
    training_country_id varchar(20),
    training_provider_id uniqueidentifier,
    training_provider_name varchar(200),
    training_provider_ukprn char(8),
    exempt_from_induction bit,
    exempt_from_induction_due_to_qts_date bit,
    degree_type_id uniqueidentifier,
    degree_type_name varchar(200),
    created_on datetime NOT NULL,
    [__Inserted] datetime,
    [__Updated] datetime
)

CREATE INDEX ix_route_migration_report_items_person_id ON trs_route_migration_report_items (person_id);
