<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPublishable>false</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="TeachingRecordSystem.Core.Tests" />
    <InternalsVisibleTo Include="TeachingRecordSystem.Core.LegacyTests" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="DataStore\Postgres\Procedures\fn_delete_person_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_delete_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_delete_tps_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_generate_trn_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_insert_person_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_insert_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_insert_tps_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_split_names_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_update_person_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_update_person_employments_person_search_attributes_v2.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_update_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_update_person_search_attributes_v2.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_update_person_search_attributes_v3.sql" />
    <None Remove="DataStore\Postgres\Procedures\fn_update_tps_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\p_refresh_name_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\p_refresh_person_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\p_refresh_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Procedures\p_refresh_person_search_attributes_v2.sql" />
    <None Remove="DataStore\Postgres\Procedures\p_refresh_person_search_attributes_v3.sql" />
    <None Remove="DataStore\Postgres\Procedures\p_refresh_tps_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Triggers\trg_delete_person_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Triggers\trg_delete_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Triggers\trg_delete_tps_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Triggers\trg_insert_person_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Triggers\trg_insert_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Triggers\trg_insert_tps_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Triggers\trg_update_person_employments_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Triggers\trg_update_person_search_attributes_v1.sql" />
    <None Remove="DataStore\Postgres\Triggers\trg_update_person_search_attributes_v2.sql" />
    <None Remove="DataStore\Postgres\Triggers\trg_update_tps_employments_person_search_attributes_v1.sql" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_delete_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_delete_previous_names_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_delete_previous_names_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_delete_tps_employments_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_delete_tps_employments_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_generate_trn_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_insert_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_insert_support_task_subject_names_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_insert_tps_employments_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_insert_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_insert_previous_names_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_insert_previous_names_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_insert_tps_employments_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_resolve_record_by_trn_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_split_names_v3.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_split_names_v4.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_update_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_update_support_task_subject_names_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_update_person_search_attributes_v3.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_update_previous_names_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_update_tps_employments_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\fn_update_tps_employments_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\p_refresh_name_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\p_refresh_person_names_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\p_refresh_person_ninos_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\p_refresh_person_search_attributes_v8.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\p_refresh_previous_names_person_search_attributes_v4.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\p_refresh_support_task_subject_names_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Procedures\p_refresh_tps_employments_person_search_attributes_v2.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_delete_previous_names_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_delete_previous_names_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_delete_tps_employments_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_delete_tps_employments_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_insert_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_insert_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_delete_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_insert_previous_names_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_insert_previous_names_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_insert_support_task_subject_names_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_insert_tps_employments_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_insert_tps_employments_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_update_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_update_person_search_attributes_v2.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_update_support_task_subject_names_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_update_previous_names_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_update_previous_names_person_search_attributes_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_update_tps_employments_person_attrs_v1.sql" />
    <EmbeddedResource Include="DataStore\Postgres\Triggers\trg_update_tps_employments_person_search_attributes_v1.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="Azure.Storage.Files.DataLake" />
    <PackageReference Include="CloudNative.CloudEvents" />
    <PackageReference Include="CloudNative.CloudEvents.SystemTextJson" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="dbup-sqlserver" />
    <PackageReference Include="DfeAnalytics.EFCore" />
    <PackageReference Include="EFCore.BulkExtensions.PostgreSql" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="EntityFrameworkCore.Projectables" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="GovukNotify" />
    <PackageReference Include="Hangfire.Core" />
    <PackageReference Include="Hangfire.NetCore" />
    <PackageReference Include="Hangfire.PostgreSql" />
    <PackageReference Include="IdentityModel" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    <PackageReference Include="Microsoft.Extensions.Azure" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="morelinq" />
    <PackageReference Include="Npgsql.DependencyInjection" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="NSign.Client" />
    <PackageReference Include="NSign.SignatureProviders" />
    <PackageReference Include="OneOf" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
    <PackageReference Include="Optional" />
    <PackageReference Include="Polly.Core" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="SerilogTimings" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Humanizer.Core" />
    <Folder Include="ApiSchema\V3\V20250627\" />
  </ItemGroup>

</Project>
