using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TeachingRecordSystem.Core.DataStore.Postgres.Models;

namespace TeachingRecordSystem.Core.DataStore.Postgres.Mappings;

public class CountryMapping : IEntityTypeConfiguration<Country>
{
    public void Configure(EntityTypeBuilder<Country> builder)
    {
        builder.HasKey(c => c.CountryId);
        builder.Property(c => c.CountryId).HasMaxLength(10);
        builder.Property(c => c.Name).IsRequired().HasMaxLength(200);
        builder.Property(c => c.OfficialName).IsRequired().HasMaxLength(200);
        builder.Property(c => c.CitizenNames).IsRequired().HasMaxLength(200);

        builder.HasData(
          new Country { CountryId = "AF", Name = "Afghanistan", OfficialName = "The Islamic Republic of Afghanistan", CitizenNames = "Afghan" },
          new Country { CountryId = "XQZ", Name = "Akrotiri", OfficialName = "Akrotiri", CitizenNames = "Not applicable" },
          new Country { CountryId = "AL", Name = "Albania", OfficialName = "The Republic of Albania", CitizenNames = "Albanian" },
          new Country { CountryId = "DZ", Name = "Algeria", OfficialName = "The People's Democratic Republic of Algeria", CitizenNames = "Algerian" },
          new Country { CountryId = "AD", Name = "Andorra", OfficialName = "The Principality of Andorra", CitizenNames = "Andorran" },
          new Country { CountryId = "AO", Name = "Angola", OfficialName = "The Republic of Angola", CitizenNames = "Angolan" },
          new Country { CountryId = "AI", Name = "Anguilla", OfficialName = "Anguilla", CitizenNames = "Anguillan" },
          new Country { CountryId = "AG", Name = "Antigua and Barbuda", OfficialName = "Antigua and Barbuda", CitizenNames = "Citizen of Antigua and Barbuda" },
          new Country { CountryId = "AR", Name = "Argentina", OfficialName = "The Argentine Republic", CitizenNames = "Argentine" },
          new Country { CountryId = "AM", Name = "Armenia", OfficialName = "The Republic of Armenia", CitizenNames = "Armenian" },
          new Country { CountryId = "AU", Name = "Australia", OfficialName = "The Commonwealth of Australia", CitizenNames = "Australian" },
          new Country { CountryId = "AT", Name = "Austria", OfficialName = "The Republic of Austria", CitizenNames = "Austrian" },
          new Country { CountryId = "AZ", Name = "Azerbaijan", OfficialName = "The Republic of Azerbaijan", CitizenNames = "Azerbaijani" },
          new Country { CountryId = "BH", Name = "Bahrain", OfficialName = "The Kingdom of Bahrain", CitizenNames = "Bahraini" },
          new Country { CountryId = "BD", Name = "Bangladesh", OfficialName = "The People's Republic of Bangladesh", CitizenNames = "Bangladeshi" },
          new Country { CountryId = "BB", Name = "Barbados", OfficialName = "Barbados", CitizenNames = "Barbadian" },
          new Country { CountryId = "BY", Name = "Belarus", OfficialName = "The Republic of Belarus", CitizenNames = "Belarusian" },
          new Country { CountryId = "BE", Name = "Belgium", OfficialName = "The Kingdom of Belgium", CitizenNames = "Belgian" },
          new Country { CountryId = "BZ", Name = "Belize", OfficialName = "Belize", CitizenNames = "Belizean" },
          new Country { CountryId = "BJ", Name = "Benin", OfficialName = "The Republic of Benin", CitizenNames = "Beninese" },
          new Country { CountryId = "BM", Name = "Bermuda", OfficialName = "Bermuda", CitizenNames = "Bermudan" },
          new Country { CountryId = "BT", Name = "Bhutan", OfficialName = "The Kingdom of Bhutan", CitizenNames = "Bhutanese" },
          new Country { CountryId = "BO", Name = "Bolivia", OfficialName = "The Plurinational State of Bolivia", CitizenNames = "Bolivian" },
          new Country { CountryId = "BA", Name = "Bosnia and Herzegovina", OfficialName = "Bosnia and Herzegovina", CitizenNames = "Citizen of Bosnia and Herzegovina" },
          new Country { CountryId = "BW", Name = "Botswana", OfficialName = "The Republic of Botswana", CitizenNames = "Botswanan" },
          new Country { CountryId = "BR", Name = "Brazil", OfficialName = "The Federative Republic of Brazil", CitizenNames = "Brazilian" },
          new Country { CountryId = "BAT", Name = "British Antarctic Territory", OfficialName = "British Antarctic Territory", CitizenNames = "Not applicable" },
          new Country { CountryId = "IO", Name = "British Indian Ocean Territory", OfficialName = "The British Indian Ocean Territory", CitizenNames = "Not applicable" },
          new Country { CountryId = "VG", Name = "British Virgin Islands", OfficialName = "The Virgin Islands", CitizenNames = "British Virgin Islander" },
          new Country { CountryId = "BN", Name = "Brunei", OfficialName = "Brunei Darussalam", CitizenNames = "Bruneian" },
          new Country { CountryId = "BG", Name = "Bulgaria", OfficialName = "The Republic of Bulgaria", CitizenNames = "Bulgarian" },
          new Country { CountryId = "BF", Name = "Burkina Faso", OfficialName = "Burkina Faso", CitizenNames = "Burkinan" },
          new Country { CountryId = "BI", Name = "Burundi", OfficialName = "The Republic of Burundi", CitizenNames = "Burundian" },
          new Country { CountryId = "KH", Name = "Cambodia", OfficialName = "The Kingdom of Cambodia", CitizenNames = "Cambodian" },
          new Country { CountryId = "CM", Name = "Cameroon", OfficialName = "The Republic of Cameroon", CitizenNames = "Cameroonian" },
          new Country { CountryId = "CA", Name = "Canada", OfficialName = "Canada", CitizenNames = "Canadian" },
          new Country { CountryId = "CV", Name = "Cape Verde", OfficialName = "The Republic of Cabo Verde", CitizenNames = "Cape Verdean" },
          new Country { CountryId = "KY", Name = "Cayman Islands", OfficialName = "Cayman Islands", CitizenNames = "Cayman Islander, Caymanian" },
          new Country { CountryId = "CF", Name = "Central African Republic", OfficialName = "The Central African Republic", CitizenNames = "Central African" },
          new Country { CountryId = "TD", Name = "Chad", OfficialName = "The Republic of Chad", CitizenNames = "Chadian" },
          new Country { CountryId = "CL", Name = "Chile", OfficialName = "The Republic of Chile", CitizenNames = "Chilean" },
          new Country { CountryId = "CN", Name = "China", OfficialName = "The People's Republic of China", CitizenNames = "Chinese" },
          new Country { CountryId = "CO", Name = "Colombia", OfficialName = "The Republic of Colombia", CitizenNames = "Colombian" },
          new Country { CountryId = "KM", Name = "Comoros", OfficialName = "The Union of the Comoros", CitizenNames = "Comoran" },
          new Country { CountryId = "CG", Name = "Congo", OfficialName = "The Republic of the Congo", CitizenNames = "Congolese (Republic of the Congo)" },
          new Country { CountryId = "CD", Name = "Congo (Democratic Republic)", OfficialName = "The Democratic Republic of the Congo", CitizenNames = "Congolese (DRC)" },
          new Country { CountryId = "CR", Name = "Costa Rica", OfficialName = "The Republic of Costa Rica", CitizenNames = "Costa Rican" },
          new Country { CountryId = "HR", Name = "Croatia", OfficialName = "The Republic of Croatia", CitizenNames = "Croatian" },
          new Country { CountryId = "CU", Name = "Cuba", OfficialName = "The Republic of Cuba", CitizenNames = "Cuban" },
          new Country { CountryId = "CY", Name = "Cyprus", OfficialName = "The Republic of Cyprus", CitizenNames = "Cypriot" },
          new Country { CountryId = "CZ", Name = "Czechia", OfficialName = "The Czech Republic", CitizenNames = "Czech" },
          new Country { CountryId = "DK", Name = "Denmark", OfficialName = "The Kingdom of Denmark", CitizenNames = "Danish" },
          new Country { CountryId = "XXD", Name = "Dhekelia", OfficialName = "Dhekelia", CitizenNames = "Not applicable" },
          new Country { CountryId = "DJ", Name = "Djibouti", OfficialName = "The Republic of Djibouti", CitizenNames = "Djiboutian" },
          new Country { CountryId = "DM", Name = "Dominica", OfficialName = "The Commonwealth of Dominica", CitizenNames = "Dominican" },
          new Country { CountryId = "DO", Name = "Dominican Republic", OfficialName = "The Dominican Republic", CitizenNames = "Citizen of the Dominican Republic" },
          new Country { CountryId = "TL", Name = "East Timor", OfficialName = "The Democratic Republic of Timor-Leste", CitizenNames = "East Timorese" },
          new Country { CountryId = "EC", Name = "Ecuador", OfficialName = "The Republic of Ecuador", CitizenNames = "Ecuadorean" },
          new Country { CountryId = "EG", Name = "Egypt", OfficialName = "The Arab Republic of Egypt", CitizenNames = "Egyptian" },
          new Country { CountryId = "SV", Name = "El Salvador", OfficialName = "The Republic of El Salvador", CitizenNames = "Salvadorean" },
          new Country { CountryId = "GB-ENG", Name = "England", OfficialName = "England", CitizenNames = "Briton, British" },
          new Country { CountryId = "GQ", Name = "Equatorial Guinea", OfficialName = "The Republic of Equatorial Guinea", CitizenNames = "Equatorial Guinean" },
          new Country { CountryId = "ER", Name = "Eritrea", OfficialName = "The State of Eritrea", CitizenNames = "Eritrean" },
          new Country { CountryId = "EE", Name = "Estonia", OfficialName = "The Republic of Estonia", CitizenNames = "Estonian" },
          new Country { CountryId = "SZ", Name = "Eswatini", OfficialName = "Kingdom of Eswatini", CitizenNames = "Swazi" },
          new Country { CountryId = "ET", Name = "Ethiopia", OfficialName = "The Federal Democratic Republic of Ethiopia", CitizenNames = "Ethiopian" },
          new Country { CountryId = "FK", Name = "Falkland Islands", OfficialName = "Falkland Islands", CitizenNames = "Falkland Islander" },
          new Country { CountryId = "FM", Name = "Federated States of Micronesia", OfficialName = "Federated States of Micronesia", CitizenNames = "Micronesian" },
          new Country { CountryId = "FJ", Name = "Fiji", OfficialName = "The Republic of Fiji", CitizenNames = "Fijian" },
          new Country { CountryId = "FI", Name = "Finland", OfficialName = "The Republic of Finland", CitizenNames = "Finnish" },
          new Country { CountryId = "FR", Name = "France", OfficialName = "The French Republic", CitizenNames = "French" },
          new Country { CountryId = "GA", Name = "Gabon", OfficialName = "The Gabonese Republic", CitizenNames = "Gabonese" },
          new Country { CountryId = "GE", Name = "Georgia", OfficialName = "Georgia", CitizenNames = "Georgian" },
          new Country { CountryId = "DE", Name = "Germany", OfficialName = "The Federal Republic of Germany", CitizenNames = "German" },
          new Country { CountryId = "GH", Name = "Ghana", OfficialName = "The Republic of Ghana", CitizenNames = "Ghanaian" },
          new Country { CountryId = "GI", Name = "Gibraltar", OfficialName = "Gibraltar", CitizenNames = "Gibraltarian" },
          new Country { CountryId = "GR", Name = "Greece", OfficialName = "The Hellenic Republic", CitizenNames = "Greek" },
          new Country { CountryId = "GD", Name = "Grenada", OfficialName = "Grenada", CitizenNames = "Grenadian" },
          new Country { CountryId = "GT", Name = "Guatemala", OfficialName = "The Republic of Guatemala", CitizenNames = "Guatemalan" },
          new Country { CountryId = "GG", Name = "Guernsey, Alderney, Sark", OfficialName = "Bailiwick of Guernsey", CitizenNames = "Guernseyman/Guernseywoman or Giernési, Ridunian, Sarkee as appropriate" },
          new Country { CountryId = "GN", Name = "Guinea", OfficialName = "The Republic of Guinea", CitizenNames = "Guinean" },
          new Country { CountryId = "GW", Name = "Guinea-Bissau", OfficialName = "The Republic of Guinea-Bissau", CitizenNames = "Citizen of Guinea-Bissau" },
          new Country { CountryId = "GY", Name = "Guyana", OfficialName = "The Co-operative Republic of Guyana", CitizenNames = "Guyanese" },
          new Country { CountryId = "HT", Name = "Haiti", OfficialName = "The Republic of Haiti", CitizenNames = "Haitian" },
          new Country { CountryId = "HN", Name = "Honduras", OfficialName = "The Republic of Honduras", CitizenNames = "Honduran" },
          new Country { CountryId = "HK", Name = "Hong Kong", OfficialName = "Hong Kong Special Administrative Region of the People's Republic of China", CitizenNames = "Hongkonger or Cantonese" },
          new Country { CountryId = "HU", Name = "Hungary", OfficialName = "Hungary", CitizenNames = "Hungarian" },
          new Country { CountryId = "IS", Name = "Iceland", OfficialName = "Iceland", CitizenNames = "Icelandic" },
          new Country { CountryId = "IN", Name = "India", OfficialName = "The Republic of India", CitizenNames = "Indian" },
          new Country { CountryId = "ID", Name = "Indonesia", OfficialName = "The Republic of Indonesia", CitizenNames = "Indonesian" },
          new Country { CountryId = "IR", Name = "Iran", OfficialName = "The Islamic Republic of Iran", CitizenNames = "Iranian" },
          new Country { CountryId = "IQ", Name = "Iraq", OfficialName = "The Republic of Iraq", CitizenNames = "Iraqi" },
          new Country { CountryId = "IE", Name = "Ireland", OfficialName = "Ireland", CitizenNames = "Irish" },
          new Country { CountryId = "IM", Name = "Isle of Man", OfficialName = "Isle of Man", CitizenNames = "Manxman/Manxwoman or Manx" },
          new Country { CountryId = "IL", Name = "Israel", OfficialName = "The State of Israel", CitizenNames = "Israeli" },
          new Country { CountryId = "IT", Name = "Italy", OfficialName = "The Italian Republic", CitizenNames = "Italian" },
          new Country { CountryId = "CI", Name = "Ivory Coast", OfficialName = "The Republic of Côte D’Ivoire", CitizenNames = "Ivorian" },
          new Country { CountryId = "JM", Name = "Jamaica", OfficialName = "Jamaica", CitizenNames = "Jamaican" },
          new Country { CountryId = "JP", Name = "Japan", OfficialName = "Japan", CitizenNames = "Japanese" },
          new Country { CountryId = "JE", Name = "Jersey", OfficialName = "Bailiwick of Jersey", CitizenNames = "Jerseyman/Jerseywoman" },
          new Country { CountryId = "JO", Name = "Jordan", OfficialName = "The Hashemite Kingdom of Jordan", CitizenNames = "Jordanian" },
          new Country { CountryId = "KZ", Name = "Kazakhstan", OfficialName = "The Republic of Kazakhstan", CitizenNames = "Kazakh" },
          new Country { CountryId = "KE", Name = "Kenya", OfficialName = "The Republic of Kenya", CitizenNames = "Kenyan" },
          new Country { CountryId = "KI", Name = "Kiribati", OfficialName = "The Republic of Kiribati", CitizenNames = "Citizen of Kiribati" },
          new Country { CountryId = "XK", Name = "Kosovo", OfficialName = "The Republic of Kosovo", CitizenNames = "Kosovan" },
          new Country { CountryId = "KW", Name = "Kuwait", OfficialName = "The State of Kuwait", CitizenNames = "Kuwaiti" },
          new Country { CountryId = "KG", Name = "Kyrgyzstan", OfficialName = "The Kyrgyz Republic", CitizenNames = "Kyrgyz" },
          new Country { CountryId = "LA", Name = "Laos", OfficialName = "The Lao People's Democratic Republic", CitizenNames = "Lao" },
          new Country { CountryId = "LV", Name = "Latvia", OfficialName = "The Republic of Latvia", CitizenNames = "Latvian" },
          new Country { CountryId = "LB", Name = "Lebanon", OfficialName = "The Lebanese Republic", CitizenNames = "Lebanese" },
          new Country { CountryId = "LS", Name = "Lesotho", OfficialName = "The Kingdom of Lesotho", CitizenNames = "Citizen of Lesotho" },
          new Country { CountryId = "LR", Name = "Liberia", OfficialName = "The Republic of Liberia", CitizenNames = "Liberian" },
          new Country { CountryId = "LY", Name = "Libya", OfficialName = "State of Libya", CitizenNames = "Libyan" },
          new Country { CountryId = "LI", Name = "Liechtenstein", OfficialName = "The Principality of Liechtenstein", CitizenNames = "Liechtenstein citizen" },
          new Country { CountryId = "LT", Name = "Lithuania", OfficialName = "The Republic of Lithuania", CitizenNames = "Lithuanian" },
          new Country { CountryId = "LU", Name = "Luxembourg", OfficialName = "The Grand Duchy of Luxembourg", CitizenNames = "Luxembourger" },
          new Country { CountryId = "MG", Name = "Madagascar", OfficialName = "The Republic of Madagascar", CitizenNames = "Citizen of Madagascar" },
          new Country { CountryId = "MW", Name = "Malawi", OfficialName = "The Republic of Malawi", CitizenNames = "Malawian" },
          new Country { CountryId = "MY", Name = "Malaysia", OfficialName = "Malaysia", CitizenNames = "Malaysian" },
          new Country { CountryId = "MV", Name = "Maldives", OfficialName = "The Republic of Maldives", CitizenNames = "Maldivian" },
          new Country { CountryId = "ML", Name = "Mali", OfficialName = "The Republic of Mali", CitizenNames = "Malian" },
          new Country { CountryId = "MT", Name = "Malta", OfficialName = "The Republic of Malta", CitizenNames = "Maltese" },
          new Country { CountryId = "MH", Name = "Marshall Islands", OfficialName = "The Republic of the Marshall Islands", CitizenNames = "Marshallese" },
          new Country { CountryId = "MR", Name = "Mauritania", OfficialName = "The Islamic Republic of Mauritania", CitizenNames = "Mauritanian" },
          new Country { CountryId = "MU", Name = "Mauritius", OfficialName = "The Republic of Mauritius", CitizenNames = "Mauritian" },
          new Country { CountryId = "MX", Name = "Mexico", OfficialName = "The United Mexican States", CitizenNames = "Mexican" },
          new Country { CountryId = "MD", Name = "Moldova", OfficialName = "The Republic of Moldova", CitizenNames = "Moldovan" },
          new Country { CountryId = "MC", Name = "Monaco", OfficialName = "The Principality of Monaco", CitizenNames = "Monegasque" },
          new Country { CountryId = "MN", Name = "Mongolia", OfficialName = "Mongolia", CitizenNames = "Mongolian" },
          new Country { CountryId = "ME", Name = "Montenegro", OfficialName = "Montenegro", CitizenNames = "Montenegrin" },
          new Country { CountryId = "MS", Name = "Montserrat", OfficialName = "Montserrat", CitizenNames = "Montserratian" },
          new Country { CountryId = "MA", Name = "Morocco", OfficialName = "The Kingdom of Morocco", CitizenNames = "Moroccan" },
          new Country { CountryId = "MZ", Name = "Mozambique", OfficialName = "The Republic of Mozambique", CitizenNames = "Mozambican" },
          new Country { CountryId = "MM", Name = "Myanmar (Burma)", OfficialName = "The Republic of the Union of Myanmar", CitizenNames = "Citizen of Myanmar" },
          new Country { CountryId = "NA", Name = "Namibia", OfficialName = "The Republic of Namibia", CitizenNames = "Namibian" },
          new Country { CountryId = "NR", Name = "Nauru", OfficialName = "The Republic of Nauru", CitizenNames = "Nauruan" },
          new Country { CountryId = "NP", Name = "Nepal", OfficialName = "Nepal", CitizenNames = "Nepalese" },
          new Country { CountryId = "NL", Name = "Netherlands", OfficialName = "The Kingdom of the Netherlands", CitizenNames = "Dutch" },
          new Country { CountryId = "NZ", Name = "New Zealand", OfficialName = "New Zealand", CitizenNames = "New Zealander" },
          new Country { CountryId = "NI", Name = "Nicaragua", OfficialName = "The Republic of Nicaragua", CitizenNames = "Nicaraguan" },
          new Country { CountryId = "NE", Name = "Niger", OfficialName = "The Republic of Niger", CitizenNames = "Nigerien" },
          new Country { CountryId = "NG", Name = "Nigeria", OfficialName = "The Federal Republic of Nigeria", CitizenNames = "Nigerian" },
          new Country { CountryId = "KP", Name = "North Korea", OfficialName = "The Democratic People's Republic of Korea", CitizenNames = "North Korean" },
          new Country { CountryId = "MK", Name = "North Macedonia", OfficialName = "Republic of North Macedonia", CitizenNames = "Macedonian" },
          new Country { CountryId = "GB-NIR", Name = "Northen Ireland", OfficialName = "Northen Ireland", CitizenNames = "Briton, British" },
          new Country { CountryId = "NO", Name = "Norway", OfficialName = "The Kingdom of Norway", CitizenNames = "Norwegian" },
          new Country { CountryId = "OM", Name = "Oman", OfficialName = "The Sultanate of Oman", CitizenNames = "Omani" },
          new Country { CountryId = "PK", Name = "Pakistan", OfficialName = "The Islamic Republic of Pakistan", CitizenNames = "Pakistani" },
          new Country { CountryId = "PW", Name = "Palau", OfficialName = "The Republic of Palau", CitizenNames = "Palauan" },
          new Country { CountryId = "PA", Name = "Panama", OfficialName = "The Republic of Panama", CitizenNames = "Panamanian" },
          new Country { CountryId = "PG", Name = "Papua New Guinea", OfficialName = "The Independent State of Papua New Guinea", CitizenNames = "Papua New Guinean" },
          new Country { CountryId = "PY", Name = "Paraguay", OfficialName = "The Republic of Paraguay", CitizenNames = "Paraguayan" },
          new Country { CountryId = "PE", Name = "Peru", OfficialName = "The Republic of Peru", CitizenNames = "Peruvian" },
          new Country { CountryId = "PH", Name = "Philippines", OfficialName = "The Republic of the Philippines", CitizenNames = "Filipino" },
          new Country { CountryId = "PN", Name = "Pitcairn, Henderson, Ducie and Oeno Islands", OfficialName = "Pitcairn, Henderson, Ducie and Oeno Islands", CitizenNames = "Pitcairn Islander or Pitcairner" },
          new Country { CountryId = "PL", Name = "Poland", OfficialName = "The Republic of Poland", CitizenNames = "Polish" },
          new Country { CountryId = "PT", Name = "Portugal", OfficialName = "The Portuguese Republic", CitizenNames = "Portuguese" },
          new Country { CountryId = "QA", Name = "Qatar", OfficialName = "The State of Qatar", CitizenNames = "Qatari" },
          new Country { CountryId = "RO", Name = "Romania", OfficialName = "Romania", CitizenNames = "Romanian" },
          new Country { CountryId = "RU", Name = "Russia", OfficialName = "The Russian Federation", CitizenNames = "Russian" },
          new Country { CountryId = "RW", Name = "Rwanda", OfficialName = "The Republic of Rwanda", CitizenNames = "Rwandan" },
          new Country { CountryId = "WS", Name = "Samoa", OfficialName = "The Independent State of Samoa", CitizenNames = "Samoan" },
          new Country { CountryId = "SM", Name = "San Marino", OfficialName = "The Republic of San Marino", CitizenNames = "San Marinese" },
          new Country { CountryId = "ST", Name = "Sao Tome and Principe", OfficialName = "The Democratic Republic of Sao Tome and Principe", CitizenNames = "Sao Tomean" },
          new Country { CountryId = "SA", Name = "Saudi Arabia", OfficialName = "The Kingdom of Saudi Arabia", CitizenNames = "Saudi Arabian" },
          new Country { CountryId = "GB-SCT", Name = "Scotland", OfficialName = "Scotland", CitizenNames = "Briton, British" },
          new Country { CountryId = "SN", Name = "Senegal", OfficialName = "The Republic of Senegal", CitizenNames = "Senegalese" },
          new Country { CountryId = "RS", Name = "Serbia", OfficialName = "The Republic of Serbia", CitizenNames = "Serbian" },
          new Country { CountryId = "SC", Name = "Seychelles", OfficialName = "The Republic of Seychelles", CitizenNames = "Citizen of Seychelles" },
          new Country { CountryId = "SL", Name = "Sierra Leone", OfficialName = "The Republic of Sierra Leone", CitizenNames = "Sierra Leonean" },
          new Country { CountryId = "SG", Name = "Singapore", OfficialName = "The Republic of Singapore", CitizenNames = "Singaporean" },
          new Country { CountryId = "SK", Name = "Slovakia", OfficialName = "The Slovak Republic", CitizenNames = "Slovak" },
          new Country { CountryId = "SI", Name = "Slovenia", OfficialName = "The Republic of Slovenia", CitizenNames = "Slovenian" },
          new Country { CountryId = "SB", Name = "Solomon Islands", OfficialName = "Solomon Islands", CitizenNames = "Solomon Islander" },
          new Country { CountryId = "SO", Name = "Somalia", OfficialName = "Federal Republic of Somalia", CitizenNames = "Somali" },
          new Country { CountryId = "ZA", Name = "South Africa", OfficialName = "The Republic of South Africa", CitizenNames = "South African" },
          new Country { CountryId = "GS", Name = "South Georgia and South Sandwich Islands", OfficialName = "South Georgia and the South Sandwich Islands", CitizenNames = "Not applicable" },
          new Country { CountryId = "KR", Name = "South Korea", OfficialName = "The Republic of Korea", CitizenNames = "South Korean" },
          new Country { CountryId = "SS", Name = "South Sudan", OfficialName = "The Republic of South Sudan", CitizenNames = "South Sudanese" },
          new Country { CountryId = "ES", Name = "Spain", OfficialName = "The Kingdom of Spain", CitizenNames = "Spanish" },
          new Country { CountryId = "LK", Name = "Sri Lanka", OfficialName = "The Democratic Socialist Republic of Sri Lanka", CitizenNames = "Sri Lankan" },
          new Country { CountryId = "SH", Name = "St Helena, Ascension and Tristan da Cunha", OfficialName = "St Helena, Ascension and Tristan da Cunha", CitizenNames = "St Helenian or Tristanian as appropriate. Ascension has no indigenous population" },
          new Country { CountryId = "KN", Name = "St Kitts and Nevis", OfficialName = "The Federation of Saint Christopher and Nevis", CitizenNames = "Citizen of St Christopher (St Kitts) and Nevis" },
          new Country { CountryId = "LC", Name = "St Lucia", OfficialName = "Saint Lucia", CitizenNames = "St Lucian" },
          new Country { CountryId = "VC", Name = "St Vincent", OfficialName = "Saint Vincent and the Grenadines", CitizenNames = "Vincentian" },
          new Country { CountryId = "SD", Name = "Sudan", OfficialName = "The Republic of the Sudan", CitizenNames = "Sudanese" },
          new Country { CountryId = "SR", Name = "Suriname", OfficialName = "The Republic of Suriname", CitizenNames = "Surinamese" },
          new Country { CountryId = "SE", Name = "Sweden", OfficialName = "The Kingdom of Sweden", CitizenNames = "Swedish" },
          new Country { CountryId = "CH", Name = "Switzerland", OfficialName = "The Swiss Confederation", CitizenNames = "Swiss" },
          new Country { CountryId = "SY", Name = "Syria", OfficialName = "The Syrian Arab Republic", CitizenNames = "Syrian" },
          new Country { CountryId = "TJ", Name = "Tajikistan", OfficialName = "The Republic of Tajikistan", CitizenNames = "Tajik" },
          new Country { CountryId = "TZ", Name = "Tanzania", OfficialName = "The United Republic of Tanzania", CitizenNames = "Tanzanian" },
          new Country { CountryId = "TH", Name = "Thailand", OfficialName = "The Kingdom of Thailand", CitizenNames = "Thai" },
          new Country { CountryId = "BS", Name = "The Bahamas", OfficialName = "The Commonwealth of The Bahamas", CitizenNames = "Bahamian" },
          new Country { CountryId = "GM", Name = "The Gambia", OfficialName = "The Republic of The Gambia", CitizenNames = "Gambian" },
          new Country { CountryId = "TG", Name = "Togo", OfficialName = "The Togolese Republic", CitizenNames = "Togolese" },
          new Country { CountryId = "TO", Name = "Tonga", OfficialName = "The Kingdom of Tonga", CitizenNames = "Tongan" },
          new Country { CountryId = "TT", Name = "Trinidad and Tobago", OfficialName = "The Republic of Trinidad and Tobago", CitizenNames = "Trinidad and Tobago citizen" },
          new Country { CountryId = "TN", Name = "Tunisia", OfficialName = "Republic of Tunisia", CitizenNames = "Tunisian" },
          new Country { CountryId = "TR", Name = "Turkey", OfficialName = "Republic of Türkiye", CitizenNames = "Turk, Turkish" },
          new Country { CountryId = "TM", Name = "Turkmenistan", OfficialName = "Turkmenistan", CitizenNames = "Turkmen" },
          new Country { CountryId = "TC", Name = "Turks and Caicos Islands", OfficialName = "Turks and Caicos Islands", CitizenNames = "Turks and Caicos Islander" },
          new Country { CountryId = "TV", Name = "Tuvalu", OfficialName = "Tuvalu", CitizenNames = "Tuvaluan" },
          new Country { CountryId = "UG", Name = "Uganda", OfficialName = "The Republic of Uganda", CitizenNames = "Ugandan" },
          new Country { CountryId = "UA", Name = "Ukraine", OfficialName = "Ukraine", CitizenNames = "Ukrainian" },
          new Country { CountryId = "AE", Name = "United Arab Emirates", OfficialName = "The United Arab Emirates", CitizenNames = "Citizen of the United Arab Emirates" },
          new Country { CountryId = "GB", Name = "United Kingdom", OfficialName = "The United Kingdom of Great Britain and Northern Ireland", CitizenNames = "Briton, British" },
          new Country { CountryId = "US", Name = "United States", OfficialName = "The United States of America", CitizenNames = "American" },
          new Country { CountryId = "UY", Name = "Uruguay", OfficialName = "The Oriental Republic of Uruguay", CitizenNames = "Uruguayan" },
          new Country { CountryId = "UZ", Name = "Uzbekistan", OfficialName = "The Republic of Uzbekistan", CitizenNames = "Uzbek" },
          new Country { CountryId = "VU", Name = "Vanuatu", OfficialName = "The Republic of Vanuatu", CitizenNames = "Citizen of Vanuatu" },
          new Country { CountryId = "VA", Name = "Vatican City", OfficialName = "Vatican City State", CitizenNames = "Vatican citizen" },
          new Country { CountryId = "VE", Name = "Venezuela", OfficialName = "The Bolivarian Republic of Venezuela", CitizenNames = "Venezuelan" },
          new Country { CountryId = "VN", Name = "Vietnam", OfficialName = "The Socialist Republic of Viet Nam", CitizenNames = "Vietnamese" },
          new Country { CountryId = "GB-WLS", Name = "Wales", OfficialName = "Wales", CitizenNames = "Briton, British" },
          new Country { CountryId = "GB-CYM", Name = "Wales", OfficialName = "Wales", CitizenNames = "Briton, British" },
          new Country { CountryId = "YE", Name = "Yemen", OfficialName = "The Republic of Yemen", CitizenNames = "Yemeni" },
          new Country { CountryId = "ZM", Name = "Zambia", OfficialName = "The Republic of Zambia", CitizenNames = "Zambian" },
          new Country { CountryId = "ZW", Name = "Zimbabwe", OfficialName = "The Republic of Zimbabwe", CitizenNames = "Zimbabwean" });
    }
}
