using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TeachingRecordSystem.Core.DataStore.Postgres.Models;
using Establishment = TeachingRecordSystem.Core.DataStore.Postgres.Models.Establishment;

namespace TeachingRecordSystem.Core.DataStore.Postgres.Mappings;

public class EstablishmentMapping : IEntityTypeConfiguration<Establishment>
{
    public void Configure(EntityTypeBuilder<Establishment> builder)
    {
        builder.ToTable("establishments");
        builder.HasKey(e => e.EstablishmentId);
        builder.Property(e => e.EstablishmentSourceId).IsRequired().HasDefaultValue(1);
        builder.HasIndex(e => e.Urn).HasDatabaseName(Establishment.UrnIndexName);
        builder.HasIndex(e => new { e.LaCode, e.EstablishmentNumber }).HasDatabaseName(Establishment.LaCodeEstablishmentNumberIndexName);
        builder.Property(e => e.Urn).HasMaxLength(6).IsFixedLength();
        builder.Property(e => e.LaCode).HasMaxLength(3).IsFixedLength();
        builder.Property(e => e.LaName).HasMaxLength(50).UseCollation(Collations.CaseInsensitive);
        builder.Property(e => e.EstablishmentNumber).HasMaxLength(4).IsFixedLength();
        builder.Property(e => e.EstablishmentName).HasMaxLength(120).UseCollation(Collations.CaseInsensitive);
        builder.Property(e => e.EstablishmentTypeCode).HasMaxLength(3);
        builder.Property(e => e.EstablishmentTypeName).HasMaxLength(100).UseCollation(Collations.CaseInsensitive);
        builder.Property(e => e.EstablishmentTypeGroupName).HasMaxLength(50);
        builder.Property(e => e.EstablishmentStatusName).HasMaxLength(50);
        builder.Property(e => e.PhaseOfEducationName).HasMaxLength(50);
        builder.Property(e => e.FreeSchoolMealsPercentage).HasPrecision(5, 2);
        builder.Property(e => e.Street).HasMaxLength(100).UseCollation(Collations.CaseInsensitive);
        builder.Property(e => e.Locality).HasMaxLength(100).UseCollation(Collations.CaseInsensitive);
        builder.Property(e => e.Address3).HasMaxLength(100).UseCollation(Collations.CaseInsensitive);
        builder.Property(e => e.Town).HasMaxLength(100).UseCollation(Collations.CaseInsensitive);
        builder.Property(e => e.County).HasMaxLength(100).UseCollation(Collations.CaseInsensitive);
        builder.Property(e => e.Postcode).HasMaxLength(10).UseCollation(Collations.CaseInsensitive);
        builder.HasIndex(e => e.EstablishmentSourceId).HasDatabaseName(Establishment.EstablishmentSourceIdIndexName);
        builder.HasOne<EstablishmentSource>().WithMany().HasForeignKey(e => e.EstablishmentSourceId).HasConstraintName("fk_establishments_establishment_source_id");

        builder.HasData(
            new() { EstablishmentId = new Guid("ede07733-97db-4e38-bff1-f3bd73b08986"), Urn = null, LaCode = "330", LaName = null, EstablishmentNumber = "0750", EstablishmentName = "Archdiocese of Birmingham", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("b6c401ad-2cdc-407e-9fb5-9a524caeab60"), Urn = null, LaCode = "340", LaName = null, EstablishmentNumber = "6006", EstablishmentName = "A.R.T.S. Education", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("571c41ae-a33a-4ac5-a2b2-467ea5c7c5c4"), Urn = null, LaCode = "383", LaName = null, EstablishmentNumber = "0751", EstablishmentName = "Workers Educational Association", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("1b1fa51d-7131-4720-b4d0-74d378aa0137"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1576", EstablishmentName = "The Peoples Learning Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("a4900bec-839f-43ee-8bca-ef79fc6fe233"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1587", EstablishmentName = "Fern Academy Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("a5d97ce7-0913-41df-ad36-bbe38ac5ab4b"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1589", EstablishmentName = "Ascendance Partnership Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("3dd6c9f6-a738-4a78-ad2d-fab4e8104184"), Urn = null, LaCode = "820", LaName = null, EstablishmentNumber = "0000", EstablishmentName = "Bedfordshire", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("58352ea6-ce6d-4225-a221-2b6a080f5a9a"), Urn = null, LaCode = "835", LaName = null, EstablishmentNumber = "0000", EstablishmentName = "Dorset", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("a37d12cf-f155-4dbf-88a0-1d30ab10c561"), Urn = null, LaCode = "855", LaName = null, EstablishmentNumber = "9097", EstablishmentName = "Kristian Thomas Company", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("d00cb67f-5da9-4430-a9a1-047490fc4df0"), Urn = null, LaCode = "875", LaName = null, EstablishmentNumber = "0000", EstablishmentName = "Cheshire", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("854d9780-b0cd-4459-a49d-df9a9502b33f"), Urn = null, LaCode = "915", LaName = null, EstablishmentNumber = "4452", EstablishmentName = "Essex Local Authority", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("e9490ca5-a696-451a-9038-33e4b5d32885"), Urn = null, LaCode = "936", LaName = null, EstablishmentNumber = "9097", EstablishmentName = "Places Leisure", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("2bd072d8-6214-4a77-b9b4-e8d77d96a030"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "0000", EstablishmentName = "Multi-Academy Trusts", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("2b9b1c3e-8057-4a68-8250-2699368e2e98"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1570", EstablishmentName = "The Collective Community Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("cb7ef0ee-41ce-4c2d-87dc-91aa968ca76c"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1572", EstablishmentName = "Synergy Education Trust Limited", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("7310b62f-454a-4d2c-8183-124acd71fd7a"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1573", EstablishmentName = "Mosaic Partnership Trust Ltd", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("1653f9ce-7a0b-4ca7-9ab1-4a2128dec8a5"), Urn = null, LaCode = "391", LaName = null, EstablishmentNumber = "0758", EstablishmentName = "Newcastle Diocesan Education Board", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("983195b9-dc5b-4f00-bf50-d44b7c87305d"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1571", EstablishmentName = "Benedict Catholic Academy Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("207144ef-ac5a-49a1-832c-5cdbc636d69a"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1578", EstablishmentName = "Mersey View Learning Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("e8939604-4570-4a56-9b8e-f53bf285e59c"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1591", EstablishmentName = "Pennine Alliance Learning Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("95a0d99b-0d4a-42a2-9528-816f5aa3b93a"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1592", EstablishmentName = "Ambition Community Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("d7bb70f1-a29a-43ee-a896-f9cbb5ac9d45"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1599", EstablishmentName = "Heritage Multi Academy Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("96c02ad6-fc23-48a0-8e68-f45b49d4f695"), Urn = null, LaCode = "836", LaName = null, EstablishmentNumber = "0000", EstablishmentName = "Poole Local Authority", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("a0f3a003-45ab-4009-8385-5358c4b16108"), Urn = null, LaCode = "870", LaName = null, EstablishmentNumber = "6019", EstablishmentName = "Aurora Rowan School", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("1c93bba7-afd2-4299-8d78-4b61197dd359"), Urn = null, LaCode = "915", LaName = null, EstablishmentNumber = "2460", EstablishmentName = "Maintained school under Essex local authority", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("7c8a6d4d-e19f-4c08-a314-348f1e159d27"), Urn = null, LaCode = "928", LaName = null, EstablishmentNumber = "4091", EstablishmentName = "Maintained school under Northamptonshire local authority", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("837c3f31-980e-4393-8790-d38289d0deba"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1600", EstablishmentName = "Tame River Educational Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("2a5b113f-04af-494e-b09f-b90ee04712f4"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1601", EstablishmentName = "The Forge Brook Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("81d8d02f-35ad-4619-9a7a-15f3fb10acf7"), Urn = null, LaCode = "873", LaName = null, EstablishmentNumber = "0751", EstablishmentName = "Workers Educational Association", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("e6b9bd0b-5a10-4a82-91f5-942b871a2d16"), Urn = null, LaCode = "918", LaName = null, EstablishmentNumber = "9450", EstablishmentName = "Worcester", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("e71de82d-d56c-4e4e-9bdf-cc8bce890593"), Urn = null, LaCode = "928", LaName = null, EstablishmentNumber = "0000", EstablishmentName = "Northamptonshire", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("86f4c057-6385-4b05-a794-9837c9a3d428"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1613", EstablishmentName = "Lighthouse Multi Academy Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("d36d3900-74ef-431c-a537-4471702f79bd"), Urn = null, LaCode = "751", LaName = null, EstablishmentNumber = "1615", EstablishmentName = "Chester Diocesan Learning Trust", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("28d30e56-c104-4b9f-8059-774fe3bc18dc"), Urn = null, LaCode = "801", LaName = null, EstablishmentNumber = "0753", EstablishmentName = "People Plus Group Ltd.", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 },
            new() { EstablishmentId = new Guid("019d868e-5ad4-4ebe-b8b0-f12e450f348a"), Urn = null, LaCode = "845", LaName = null, EstablishmentNumber = "2032", EstablishmentName = "Thornton Grove Academy", EstablishmentTypeCode = null, EstablishmentTypeName = null, EstablishmentTypeGroupCode = null, EstablishmentTypeGroupName = null, EstablishmentStatusCode = null, EstablishmentStatusName = null, PhaseOfEducationCode = null, PhaseOfEducationName = null, NumberOfPupils = null, FreeSchoolMealsPercentage = null, Street = null, Locality = null, Address3 = null, Town = null, County = null, Postcode = null, EstablishmentSourceId = 2 }
        );
    }
}
