using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TeachingRecordSystem.Core.DataStore.Postgres.Models;

namespace TeachingRecordSystem.Core.DataStore.Postgres.Mappings;

public class TpsEstablishmentTypeMapping : IEntityTypeConfiguration<TpsEstablishmentType>
{
    public void Configure(EntityTypeBuilder<TpsEstablishmentType> builder)
    {
        builder.ToTable("tps_establishment_types");
        builder.HasKey(e => e.TpsEstablishmentTypeId);
        builder.Property(e => e.EstablishmentRangeFrom).HasMaxLength(4).IsFixedLength().IsRequired();
        builder.Property(e => e.EstablishmentRangeTo).HasMaxLength(4).IsFixedLength().IsRequired();
        builder.Property(e => e.Description).HasMaxLength(300).IsRequired();
        builder.Property(e => e.ShortDescription).HasMaxLength(120).IsRequired();

        builder.HasData(
            new() { TpsEstablishmentTypeId = 1, EstablishmentRangeFrom = "0001", EstablishmentRangeTo = "0099", Description = "Homes set up under the Children and Young Persons Act (e.g. Community Homes)", ShortDescription = "Homes set up under the Children and Young Persons Act (e.g. Community Homes)" },
            new() { TpsEstablishmentTypeId = 2, EstablishmentRangeFrom = "0200", EstablishmentRangeTo = "0399", Description = "Homes set up under the Children and Young Persons Act (e.g. Community Homes)", ShortDescription = "Homes set up under the Children and Young Persons Act (e.g. Community Homes)" },
            new() { TpsEstablishmentTypeId = 3, EstablishmentRangeFrom = "0400", EstablishmentRangeTo = "0524", Description = "Training and occupation centres and other DSS establishments (except day nurseries)", ShortDescription = "Training and occupation centres and other DSS establishments (except day nurseries)" },
            new() { TpsEstablishmentTypeId = 4, EstablishmentRangeFrom = "0525", EstablishmentRangeTo = "0549", Description = "Special Hospitals provided under Part VII of the Mental Health Act 1959", ShortDescription = "Special Hospitals provided under Part VII of the Mental Health Act 1959" },
            new() { TpsEstablishmentTypeId = 5, EstablishmentRangeFrom = "0550", EstablishmentRangeTo = "0574", Description = "Teachers' Superannuation (Army Civilian Lecturer) Scheme 1951 Schools or schools formerly under that Scheme", ShortDescription = "Teachers' Superannuation (Army Civilian Lecturer) Scheme 1951 Schools or schools formerly under that Scheme" },
            new() { TpsEstablishmentTypeId = 6, EstablishmentRangeFrom = "0575", EstablishmentRangeTo = "0599", Description = "Education Forum", ShortDescription = "Education Forum" },
            new() { TpsEstablishmentTypeId = 7, EstablishmentRangeFrom = "0600", EstablishmentRangeTo = "0600", Description = "CAY", ShortDescription = "CAY" },
            new() { TpsEstablishmentTypeId = 8, EstablishmentRangeFrom = "0601", EstablishmentRangeTo = "0601", Description = "PAY", ShortDescription = "PAY" },
            new() { TpsEstablishmentTypeId = 9, EstablishmentRangeFrom = "0625", EstablishmentRangeTo = "0625", Description = "DSS day nurseries", ShortDescription = "DSS day nurseries" },
            new() { TpsEstablishmentTypeId = 10, EstablishmentRangeFrom = "0626", EstablishmentRangeTo = "0674", Description = "Schools and institutions controlled by other government departments", ShortDescription = "Schools and institutions controlled by other government departments" },
            new() { TpsEstablishmentTypeId = 11, EstablishmentRangeFrom = "0675", EstablishmentRangeTo = "0750", Description = "Employment under voluntary youth organisations", ShortDescription = "Employment under voluntary youth organisations" },
            new() { TpsEstablishmentTypeId = 12, EstablishmentRangeFrom = "0100", EstablishmentRangeTo = "0199", Description = "Employment under voluntary youth organisations", ShortDescription = "Employment under voluntary youth organisations" },
            new() { TpsEstablishmentTypeId = 13, EstablishmentRangeFrom = "0751", EstablishmentRangeTo = "0939", Description = "Employment under adult and miscellaneous organisations", ShortDescription = "Employment under adult and miscellaneous organisations" },
            new() { TpsEstablishmentTypeId = 14, EstablishmentRangeFrom = "0940", EstablishmentRangeTo = "0949", Description = "Playing for Success Centres", ShortDescription = "Playing for Success Centres" },
            new() { TpsEstablishmentTypeId = 15, EstablishmentRangeFrom = "1000", EstablishmentRangeTo = "1099", Description = "LA nursery schools", ShortDescription = "LA nursery schools" },
            new() { TpsEstablishmentTypeId = 16, EstablishmentRangeFrom = "1100", EstablishmentRangeTo = "1150", Description = "Pupil referral units", ShortDescription = "Pupil referral units" },
            new() { TpsEstablishmentTypeId = 75, EstablishmentRangeFrom = "1151", EstablishmentRangeTo = "1799", Description = "LA nursery schools", ShortDescription = "LA nursery schools" },
            new() { TpsEstablishmentTypeId = 17, EstablishmentRangeFrom = "1800", EstablishmentRangeTo = "1899", Description = "Direct-grant nursery schools", ShortDescription = "Direct-grant nursery schools" },
            new() { TpsEstablishmentTypeId = 18, EstablishmentRangeFrom = "1900", EstablishmentRangeTo = "1999", Description = "Independent nursery education establishment recognised as efficient", ShortDescription = "Independent nursery education establishment recognised as efficient" },
            new() { TpsEstablishmentTypeId = 19, EstablishmentRangeFrom = "2000", EstablishmentRangeTo = "3999", Description = "Maintained primary schools and schools which have converted to academies", ShortDescription = "Maintained primary schools and schools which have converted to academies" },
            new() { TpsEstablishmentTypeId = 20, EstablishmentRangeFrom = "4000", EstablishmentRangeTo = "4999", Description = "Maintained secondary schools and schools which have converted to academies", ShortDescription = "Maintained secondary schools and schools which have converted to academies" },
            new() { TpsEstablishmentTypeId = 21, EstablishmentRangeFrom = "5000", EstablishmentRangeTo = "5099", Description = "Direct-grant schools (recorded up to October 1980)", ShortDescription = "Direct-grant schools (recorded up to October 1980)" },
            new() { TpsEstablishmentTypeId = 22, EstablishmentRangeFrom = "5100", EstablishmentRangeTo = "5198", Description = "Practical instruction centres (not all such centres have been allocated individual numbers but where a number has already been allocated its use is continued. All new centres are numbered 5199)", ShortDescription = "Practical instruction centres" },
            new() { TpsEstablishmentTypeId = 23, EstablishmentRangeFrom = "5200", EstablishmentRangeTo = "5299", Description = "Grant-maintained primary/middle deemed primary schools and schools which have converted to academies", ShortDescription = "Grant-maintained primary/middle deemed primary schools and schools which have converted to academies" },
            new() { TpsEstablishmentTypeId = 24, EstablishmentRangeFrom = "5300", EstablishmentRangeTo = "5399", Description = "Camps, holiday classes etc.", ShortDescription = "Camps, holiday classes etc." },
            new() { TpsEstablishmentTypeId = 25, EstablishmentRangeFrom = "5400", EstablishmentRangeTo = "5499", Description = "Grant-maintained secondary/middle deemed secondary schools and schools which have converted to academies", ShortDescription = "Grant-maintained secondary/middle deemed secondary schools and schools which have converted to academies" },
            new() { TpsEstablishmentTypeId = 26, EstablishmentRangeFrom = "5500", EstablishmentRangeTo = "5548", Description = "Immigrant centres", ShortDescription = "Immigrant centres" },
            new() { TpsEstablishmentTypeId = 27, EstablishmentRangeFrom = "5601", EstablishmentRangeTo = "5899", Description = "Grant-maintained primary, middle and secondary schools (overflow) schools which have converted to academies", ShortDescription = "Grant-maintained primary, middle and secondary schools (overflow) schools which have converted to academies" },
            new() { TpsEstablishmentTypeId = 28, EstablishmentRangeFrom = "5900", EstablishmentRangeTo = "5949", Description = "Grant-maintained schools (formally Independent) schools which have converted to academies", ShortDescription = "Grant-maintained schools (formally Independent) schools which have converted to academies" },
            new() { TpsEstablishmentTypeId = 29, EstablishmentRangeFrom = "5950", EstablishmentRangeTo = "5999", Description = "Grant-maintained special schools and schools which have converted to academies", ShortDescription = "Grant-maintained special schools and schools which have converted to academies" },
            new() { TpsEstablishmentTypeId = 30, EstablishmentRangeFrom = "6000", EstablishmentRangeTo = "6899", Description = "Independent schools", ShortDescription = "Independent schools" },
            new() { TpsEstablishmentTypeId = 31, EstablishmentRangeFrom = "6900", EstablishmentRangeTo = "6904", Description = "City technology colleges", ShortDescription = "City technology colleges" },
            new() { TpsEstablishmentTypeId = 32, EstablishmentRangeFrom = "6905", EstablishmentRangeTo = "6924", Description = "City Academies", ShortDescription = "City Academies" },
            new() { TpsEstablishmentTypeId = 33, EstablishmentRangeFrom = "7000", EstablishmentRangeTo = "7749", Description = "Special schools (except as below)", ShortDescription = "Special schools" },
            new() { TpsEstablishmentTypeId = 34, EstablishmentRangeFrom = "7750", EstablishmentRangeTo = "7798", Description = "Special schools for nursery age children", ShortDescription = "Special schools for nursery age children" },
            new() { TpsEstablishmentTypeId = 35, EstablishmentRangeFrom = "7800", EstablishmentRangeTo = "7899", Description = "Boarding homes for handicapped pupils", ShortDescription = "Boarding homes for handicapped pupils" },
            new() { TpsEstablishmentTypeId = 36, EstablishmentRangeFrom = "7900", EstablishmentRangeTo = "7999", Description = "Establishments for further education and training of disabled persons", ShortDescription = "Establishments for further education and training of disabled persons" },
            new() { TpsEstablishmentTypeId = 37, EstablishmentRangeFrom = "8000", EstablishmentRangeTo = "8149", Description = "Maintained and assisted major FE establishments (not included below)", ShortDescription = "Maintained and assisted major FE establishments" },
            new() { TpsEstablishmentTypeId = 38, EstablishmentRangeFrom = "8150", EstablishmentRangeTo = "8199", Description = "Maintained and assisted art establishments", ShortDescription = "Maintained and assisted art establishments" },
            new() { TpsEstablishmentTypeId = 39, EstablishmentRangeFrom = "8200", EstablishmentRangeTo = "8219", Description = "Direct-grant major FE establishments", ShortDescription = "Direct-grant major FE establishments" },
            new() { TpsEstablishmentTypeId = 40, EstablishmentRangeFrom = "8220", EstablishmentRangeTo = "8269", Description = "Independent (Efficient-Rules 16) FE establishments", ShortDescription = "Independent (Efficient-Rules 16) FE establishments" },
            new() { TpsEstablishmentTypeId = 41, EstablishmentRangeFrom = "8270", EstablishmentRangeTo = "8284", Description = "National colleges", ShortDescription = "National colleges" },
            new() { TpsEstablishmentTypeId = 42, EstablishmentRangeFrom = "8300", EstablishmentRangeTo = "8349", Description = "LA farm institutes", ShortDescription = "LA farm institutes" },
            new() { TpsEstablishmentTypeId = 43, EstablishmentRangeFrom = "8350", EstablishmentRangeTo = "8389", Description = "LA agricultural centres", ShortDescription = "LA agricultural centres" },
            new() { TpsEstablishmentTypeId = 44, EstablishmentRangeFrom = "8390", EstablishmentRangeTo = "8399", Description = "Direct-grant and independent agricultural establishments", ShortDescription = "Direct-grant and independent agricultural establishments" },
            new() { TpsEstablishmentTypeId = 45, EstablishmentRangeFrom = "8400", EstablishmentRangeTo = "8499", Description = "LA youth welfare", ShortDescription = "LA youth welfare" },
            new() { TpsEstablishmentTypeId = 46, EstablishmentRangeFrom = "8500", EstablishmentRangeTo = "8599", Description = "LA adult welfare", ShortDescription = "LA adult welfare" },
            new() { TpsEstablishmentTypeId = 47, EstablishmentRangeFrom = "8600", EstablishmentRangeTo = "8699", Description = "Sixth form colleges", ShortDescription = "Sixth form colleges" },
            new() { TpsEstablishmentTypeId = 48, EstablishmentRangeFrom = "8700", EstablishmentRangeTo = "8898", Description = "Polytechnics/New Style Universities", ShortDescription = "Polytechnics/New Style Universities" },
            new() { TpsEstablishmentTypeId = 49, EstablishmentRangeFrom = "9300", EstablishmentRangeTo = "9599", Description = "LA colleges of education", ShortDescription = "LA colleges of education" },
            new() { TpsEstablishmentTypeId = 50, EstablishmentRangeFrom = "9600", EstablishmentRangeTo = "9899", Description = "Voluntary colleges of education", ShortDescription = "Voluntary colleges of education" },
            new() { TpsEstablishmentTypeId = 51, EstablishmentRangeFrom = "0950", EstablishmentRangeTo = "0950", Description = "Teacher /organiser (employed primarily as a teacher)", ShortDescription = "Teacher /organiser (employed primarily as a teacher)" },
            new() { TpsEstablishmentTypeId = 52, EstablishmentRangeFrom = "0951", EstablishmentRangeTo = "0951", Description = "Divided service between Primary and Secondary Schools", ShortDescription = "Divided service between Primary and Secondary Schools" },
            new() { TpsEstablishmentTypeId = 53, EstablishmentRangeFrom = "0952", EstablishmentRangeTo = "0952", Description = "Divided service between Further Education and P & S Schools", ShortDescription = "Divided service between Further Education and P & S Schools" },
            new() { TpsEstablishmentTypeId = 54, EstablishmentRangeFrom = "0954", EstablishmentRangeTo = "0954", Description = "Adult Miscellaneous Organisation", ShortDescription = "Adult Miscellaneous Organisation" },
            new() { TpsEstablishmentTypeId = 55, EstablishmentRangeFrom = "7799", EstablishmentRangeTo = "7799", Description = "Divided service between Special Schools", ShortDescription = "Divided service between Special Schools" },
            new() { TpsEstablishmentTypeId = 56, EstablishmentRangeFrom = "8999", EstablishmentRangeTo = "8999", Description = "Divided service between FE establishments", ShortDescription = "Divided service between FE establishments" },
            new() { TpsEstablishmentTypeId = 57, EstablishmentRangeFrom = "0953", EstablishmentRangeTo = "0953", Description = "Adult Miscellaneous Organisation (not allocated an Estab No) - ie teacher paid under FE document, employed providing FE or Adult Education (eg Community College)", ShortDescription = "Adult Miscellaneous Organisation (not allocated an Estab No)" },
            new() { TpsEstablishmentTypeId = 58, EstablishmentRangeFrom = "0955", EstablishmentRangeTo = "0955", Description = "Teacher employed by Ministry of Defence (UK based)", ShortDescription = "Teacher employed by Ministry of Defence (UK based)" },
            new() { TpsEstablishmentTypeId = 59, EstablishmentRangeFrom = "0960", EstablishmentRangeTo = "0960", Description = "Unattached regular engagement in Primary Schools - ie Permanent 'supply' teacher under contract", ShortDescription = "Unattached regular engagement in Primary Schools - ie Permanent 'supply' teacher under contract" },
            new() { TpsEstablishmentTypeId = 60, EstablishmentRangeFrom = "0961", EstablishmentRangeTo = "0961", Description = "Unattached regular engagement in Secondary or P & S - ie Permanent 'supply' teacher under contract", ShortDescription = "Unattached regular engagement in Secondary or P & S - ie Permanent 'supply' teacher under contract" },
            new() { TpsEstablishmentTypeId = 61, EstablishmentRangeFrom = "0962", EstablishmentRangeTo = "0962", Description = "Visiting Teacher Primary - peripatetic teacher (eg specialist subject teacher visiting different schools)", ShortDescription = "Visiting Teacher Primary - peripatetic teacher (eg specialist subject teacher visiting different schools)" },
            new() { TpsEstablishmentTypeId = 62, EstablishmentRangeFrom = "0963", EstablishmentRangeTo = "0963", Description = "Visiting Teacher Secondary or P & S - peripatetic teacher (eg specialist subject teacher visiting different schools)", ShortDescription = "Visiting Teacher Secondary or P & S - peripatetic teacher (eg specialist subject teacher visiting different schools)" },
            new() { TpsEstablishmentTypeId = 63, EstablishmentRangeFrom = "0964", EstablishmentRangeTo = "0964", Description = "P & S teaching under Section 56 of Education Act 1944 - ie teaching other than at a school (eg at home or in a hospital, or teachers in penal establishments)", ShortDescription = "P & S teaching under Section 56 of Education Act 1944 - ie teaching other than at a school" },
            new() { TpsEstablishmentTypeId = 64, EstablishmentRangeFrom = "0965", EstablishmentRangeTo = "0965", Description = "Peripatetic support wholly for SEN or disabled not in a special school.", ShortDescription = "Peripatetic support wholly for SEN or disabled not in a special school." },
            new() { TpsEstablishmentTypeId = 65, EstablishmentRangeFrom = "0966", EstablishmentRangeTo = "0966", Description = "School supply teacher - whose contract is terminable without notice. Teacher who is employed temporarily in place of a regularly employed teacher. Teacher has made a part-time election.", ShortDescription = "School supply teacher - whose contract is terminable without notice" },
            new() { TpsEstablishmentTypeId = 66, EstablishmentRangeFrom = "0970", EstablishmentRangeTo = "0971", Description = "Full-time Organiser - employment involves the performance of duties in connection with the provision of education or service ancillary to education (accepted in TPS only if previously accepted under 1967 Teachers' Pension Regulations)", ShortDescription = "Full-time Organiser" },
            new() { TpsEstablishmentTypeId = 67, EstablishmentRangeFrom = "0972", EstablishmentRangeTo = "0972", Description = "Full and Part-Time Youth and Community Worker", ShortDescription = "Full and Part-Time Youth and Community Worker" },
            new() { TpsEstablishmentTypeId = 68, EstablishmentRangeFrom = "5199", EstablishmentRangeTo = "5199", Description = "Service as a teacher in Practical Instruction Centres - providing P & S education (previously allocated individual numbers in range 5100-5199)(not schools - unattached units). (Service other than as a teacher would have to be considered by the Department)", ShortDescription = "Service as a teacher in Practical Instruction Centres - providing P & S education" },
            new() { TpsEstablishmentTypeId = 69, EstablishmentRangeFrom = "5549", EstablishmentRangeTo = "5549", Description = "Service as a teacher in Remedial Centres and Support Units - providing P & S education (not schools - unattached units). (Service other than as a teacher would have to be considered by the Department", ShortDescription = "Service as a teacher in Remedial Centres and Support Units - providing P & S education (not schools - unattached units)" },
            new() { TpsEstablishmentTypeId = 70, EstablishmentRangeFrom = "5599", EstablishmentRangeTo = "5599", Description = "Service as a teacher in any other P & S Centre (ie not PI or Remedial)(eg Assessment Centres outdoor pursuit centres, Teacher Centres [if paid P & S]). Service other than as a teacher would have to be considered by Teachers' Pensions)", ShortDescription = "Service as a teacher in any other P & S Centre (ie not PI or Remedial)" },
            new() { TpsEstablishmentTypeId = 71, EstablishmentRangeFrom = "5600", EstablishmentRangeTo = "5600", Description = "Service in Intermediate Treatment Centres - providing P & S education (not schools - unattached units)", ShortDescription = "Service in Intermediate Treatment Centres - providing P & S education (not schools - unattached units)" },
            new() { TpsEstablishmentTypeId = 72, EstablishmentRangeFrom = "9099", EstablishmentRangeTo = "9099", Description = "Function Provider within a LEA", ShortDescription = "Function Provider within a LEA" },
            new() { TpsEstablishmentTypeId = 73, EstablishmentRangeFrom = "8899", EstablishmentRangeTo = "8899", Description = "Adult Education Service (residential adult education estabs have numbers allocated in range 8290-8294). Teacher Centres if paid on FE Scales, Adult Literacy Scheme staff (LA)", ShortDescription = "Adult Education Service" },
            new() { TpsEstablishmentTypeId = 74, EstablishmentRangeFrom = "0999", EstablishmentRangeTo = "0999", Description = "Service of any other kind (eg full-time educational officers in penal estabs Job Creation Schemes). Normally this code will not be used where a teacher is in receipt of a mandatory Burnham salary", ShortDescription = "Service of any other kind (eg full-time educational officers in penal estabs Job Creation Schemes)" }
            );
    }
}
