create table trs_trn_request_metadata
(
    application_user_id uniqueidentifier NOT NULL,
    request_id varchar(100) NOT NULL,
    created_on datetime,
    identity_verified bit,
    email_address nvarchar(max),
    work_email_address nvarchar(max),
    one_login_user_subject varchar(255),
    first_name nvarchar(max),
    middle_name nvarchar(max),
    last_name nvarchar(max),
    previous_first_name nvarchar(max),
    previous_middle_name nvarchar(max),
    previous_last_name nvarchar(max),
    name nvarchar(max),
    date_of_birth date,
    potential_duplicate bit,
    national_insurance_number nvarchar(max),
    gender integer,
    address_line1 nvarchar(max),
    address_line2 nvarchar(max),
    address_line3 nvarchar(max),
    city nvarchar(max),
    postcode nvarchar(max),
    country nvarchar(max),
    trn_token nvarchar(max),
    resolved_person_id uniqueidentifier,
    status integer,
    npq_working_in_educational_setting bit,
    npq_application_id nvarchar(max),
    npq_name nvarchar(max),
    npq_training_provider nvarchar(max),
    npq_evidence_file_id uniqueidentifier,
    npq_evidence_file_name nvarchar(max),
    matches nvarchar(max),
    [__Inserted] datetime,
    [__Updated] datetime,
    primary key (application_user_id, request_id)
)
