create table trs_users
(
    user_id uniqueidentifier primary key,
    active bit not null,
    user_type int not null,
    name nvarchar(200),
    email nvarchar(200),
    azure_ad_user_id nvarchar(100),
    dqt_user_id uniqueidentifier,
    api_roles nvarchar(max),
    one_login_client_id nvarchar(50),
    one_login_private_key_pem nvarchar(max),
    is_oidc_client bit,
    one_login_authentication_scheme_name nvarchar(50),
    one_login_post_logout_redirect_uri_path nvarchar(100),
    one_login_redirect_uri_path nvarchar(100),
    client_id nvarchar(50),
    client_secret nvarchar(200),
    post_logout_redirect_uris nvarchar(max),
    redirect_uris nvarchar(max),
    role nvarchar(50),
    short_name nvarchar(25),
    [__Inserted] datetime,
    [__Updated] datetime,
)
