namespace TeachingRecordSystem.SupportUi.Services.SupportTasks;

public record SearchOneLoginUserIdVerificationRequestsOptions(OneLoginIdVerificationRequestsSortByOption SortBy, SortDirection SortDirection);
