namespace TeachingRecordSystem.SupportUi.Services.SupportTasks;

public record SearchOneLoginUserIdVerificationSupportTasksOptions(OneLoginIdVerificationSupportTasksSortByOption SortBy, SortDirection SortDirection);
