<Project>
  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.10.0" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.11" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.11" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="CliWrap" />
    <Using Include="CliWrap.Buffered" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Utils.cs" />
  </ItemGroup>
</Project>
