<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
    <IsPublishable>false</IsPublishable>
    <UserSecretsId>TeachingRecordSystemTests</UserSecretsId>
    <NoWarn>$(NoWarn);CA1816</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Faker.Net" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Respawn" />
    <!-- SSH.NET is explicitly included so we upgrade from a version with vulnerabilities (pulled in from Testcontainers) -->
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit.v3.assert" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TeachingRecordSystem.Core\TeachingRecordSystem.Core.csproj" />
  </ItemGroup>

</Project>
