namespace TeachingRecordSystem.Core.Models;

public enum ProcessType
{
    PersonMigratingFromDqt = 1,
    PersonCreatingInDqt = 2,
    PersonImportingIntoDqt = 3,
    PersonUpdatingInDqt = 4,
    PersonDeactivatingInDqt = 5,
    PersonReactivatingInDqt = 6,
    PersonMergingInDqt = 7,
    SupportTaskDeleting = 8,
    TrnRequestResetting = 9,
    NotifyingTrnRecipient = 10,
    NoteCreating = 11,
    ChangeOfDateOfBirthRequestCreating = 12,
    ChangeOfNameRequestCreating = 13,
    ApiTrnRequestCreating = 14,
    NpqTrnRequestTaskCreating = 15,
    ApiTrnRequestResolving = 16,
    NpqTrnRequestApproving = 18,
    NpqTrnRequestRejecting = 19,
    TrnRequestManualChecksNeededTaskCompleting = 20,
    TeacherPensionsDuplicateSupportTaskResolvingWithMerge = 21,
    TeacherPensionsDuplicateSupportTaskResolvingWithoutMerge = 22,
    OneLoginUserIdVerificationSupportTaskCompleting = 23,
    PersonCreating = 24,
    PersonDetailsUpdating = 25,
    PersonDeactivating = 26,
    PersonReactivating = 27,
    TeacherPensionsRecordImporting = 28,
    PersonMerging = 29,
    ChangeOfNameRequestApproving = 30,
    ChangeOfDateOfBirthRequestApproving = 31,
    OneLoginUserIdVerificationSupportTaskSaving = 32,
    OneLoginUserRecordMatchingSupportTaskSaving = 33,
    OneLoginUserRecordMatchingSupportTaskCompleting = 34,
    TeacherSigningIn = 36,
    PersonOneLoginUserConnecting = 37,
    PersonOneLoginUserDisconnecting = 38,
    AlertCreating = 39,
    AlertUpdating = 40,
    AlertDeleting = 41
}
