//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QualifiedTeachersApi.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QualifiedTeachersApi.Properties.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request must contain IttProviderUkprn or IttProviderName or neither..
        /// </summary>
        public static string ErrorMessage_EitherIttProviderNameOrIttProviderUkprn {
            get {
                return ResourceManager.GetString("ErrorMessage.EitherIttProviderNameOrIttProviderUkprn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age must be 0-19 inclusive..
        /// </summary>
        public static string ErrorMessages_AgeMustBe0To19Inclusive {
            get {
                return ResourceManager.GetString("ErrorMessages.AgeMustBe0To19Inclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Age to&apos; cannot be less than &apos;age from&apos;..
        /// </summary>
        public static string ErrorMessages_AgeToCannotBeLessThanAgeFrom {
            get {
                return ResourceManager.GetString("ErrorMessages.AgeToCannotBeLessThanAgeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date is out of expected range..
        /// </summary>
        public static string ErrorMessages_BirthDateIsOutOfRange {
            get {
                return ResourceManager.GetString("ErrorMessages.BirthDateIsOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date must be in format yyyy-MM-dd.
        /// </summary>
        public static string ErrorMessages_InvalidBirthDate {
            get {
                return ResourceManager.GetString("ErrorMessages.InvalidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requestId can only contain characters a-z, digits, underscores and dashes..
        /// </summary>
        public static string ErrorMessages_RequestIdCanOnlyContainCharactersDigitsUnderscoresAndDashes {
            get {
                return ResourceManager.GetString("ErrorMessages.RequestIdCanOnlyContainCharactersDigitsUnderscoresAndDashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to requestId must be 100 characters or fewer.
        /// </summary>
        public static string ErrorMessages_RequestIdMustBe100CharactersOrFewer {
            get {
                return ResourceManager.GetString("ErrorMessages.RequestIdMustBe100CharactersOrFewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRN must consist of 7 digits.
        /// </summary>
        public static string ErrorMessages_TRNMustBe7Digits {
            get {
                return ResourceManager.GetString("ErrorMessages.TRNMustBe7Digits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher with specified TRN not found.
        /// </summary>
        public static string Errors_10001_Title {
            get {
                return ResourceManager.GetString("Errors.10001.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple teachers found.
        /// </summary>
        public static string Errors_10002_Title {
            get {
                return ResourceManager.GetString("Errors.10002.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher already has QTS/EYTS date.
        /// </summary>
        public static string Errors_10003_Title {
            get {
                return ResourceManager.GetString("Errors.10003.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher has multiple incomplete ITT records.
        /// </summary>
        public static string Errors_10004_Title {
            get {
                return ResourceManager.GetString("Errors.10004.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher has no incomplete ITT record.
        /// </summary>
        public static string Errors_10005_Title {
            get {
                return ResourceManager.GetString("Errors.10005.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher has no QTS record.
        /// </summary>
        public static string Errors_10006_Title {
            get {
                return ResourceManager.GetString("Errors.10006.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher has multiple QTS records.
        /// </summary>
        public static string Errors_10007_Title {
            get {
                return ResourceManager.GetString("Errors.10007.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation not found.
        /// </summary>
        public static string Errors_10008_Title {
            get {
                return ResourceManager.GetString("Errors.10008.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject not found.
        /// </summary>
        public static string Errors_10009_Title {
            get {
                return ResourceManager.GetString("Errors.10009.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country not found.
        /// </summary>
        public static string Errors_10010_Title {
            get {
                return ResourceManager.GetString("Errors.10010.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProgrammeType cannot be change.
        /// </summary>
        public static string Errors_10011_Title {
            get {
                return ResourceManager.GetString("Errors.10011.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ITT qualification not found.
        /// </summary>
        public static string Errors_10012_Title {
            get {
                return ResourceManager.GetString("Errors.10012.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HE qualification not found.
        /// </summary>
        public static string Errors_10013_Title {
            get {
                return ResourceManager.GetString("Errors.10013.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to unlock teacher with active sanctions.
        /// </summary>
        public static string Errors_10014_Title {
            get {
                return ResourceManager.GetString("Errors.10014.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher with specified TsPersonId not found.
        /// </summary>
        public static string Errors_10015_Title {
            get {
                return ResourceManager.GetString("Errors.10015.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another teacher has the specified TsPersonId assigned.
        /// </summary>
        public static string Errors_10016_Title {
            get {
                return ResourceManager.GetString("Errors.10016.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher already has TsPersonId defined.
        /// </summary>
        public static string Errors_10017_Title {
            get {
                return ResourceManager.GetString("Errors.10017.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husid registered for an existing teacher.
        /// </summary>
        public static string Errors_10018_Title {
            get {
                return ResourceManager.GetString("Errors.10018.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionDate cannot be in the future.
        /// </summary>
        public static string Errors_10019_Title {
            get {
                return ResourceManager.GetString("Errors.10019.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple qualifications with qualification type..
        /// </summary>
        public static string Errors_10020_Title {
            get {
                return ResourceManager.GetString("Errors.10020.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update npq qualifications not created by API.
        /// </summary>
        public static string Errors_10021_Title {
            get {
                return ResourceManager.GetString("Errors.10021.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed date cannot be before 1/11/2021.
        /// </summary>
        public static string Errors_10022_Title {
            get {
                return ResourceManager.GetString("Errors.10022.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with specified UserId not found.
        /// </summary>
        public static string Errors_10023_Title {
            get {
                return ResourceManager.GetString("Errors.10023.Title", resourceCulture);
            }
        }
    }
}
