name: Deploy pre-production environment

on:
  workflow_call:
    inputs:
      api_docker_image:
        type: string
        required: true
      cli_docker_image:
        type: string
        required: true
      ui_docker_image:
        type: string
        required: true
  workflow_dispatch:

concurrency: deploy_preprod
jobs:
  package:
    name: Package application
    if: inputs.api_docker_image == ''
    uses: ./.github/workflows/package.yml
    secrets: inherit

  deploy_aks:
    name: Deploy to AKS
    needs: package
    if: always() && (needs.package.result == 'success' || needs.package.result == 'skipped')
    runs-on: ubuntu-latest

    environment:
      name: pre-production_aks

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/actions/deploy-aks-environment
      id: deploy
      with:
        environment_name: pre-production
        api_docker_image: ${{ inputs.api_docker_image || needs.package.outputs.api_docker_image }}
        cli_docker_image: ${{ inputs.cli_docker_image || needs.package.outputs.cli_docker_image }}
        ui_docker_image: ${{ inputs.ui_docker_image || needs.package.outputs.ui_docker_image }}
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
