name: Deploy test environment

on:
  workflow_call:
    inputs:
      docker_image:
        type: string
        required: true

  workflow_dispatch:
    inputs:
      docker_image:
        required: true
        type: string

concurrency: deploy_test
jobs:
  deploy_aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/actions/deploy-aks-environment
      id: deploy
      with:
        environment_name: test
        docker_image: ${{ inputs.docker_image }}
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
