name: Deploy test environment

on:
  workflow_call:
    inputs:
      api_docker_image:
        type: string
        required: true
      cli_docker_image:
        type: string
        required: true
      ui_docker_image:
        type: string
        required: true

concurrency: deploy_test
jobs:
  deploy_aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest

    environment:
      name: test_aks

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/actions/deploy-aks-environment
      id: deploy
      with:
        environment_name: test
        api_docker_image: ${{ inputs.api_docker_image }}
        cli_docker_image: ${{ inputs.cli_docker_image }}
        ui_docker_image: ${{ inputs.ui_docker_image }}
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

