name: Deploy dev environment

on:
  workflow_call:
    inputs:
      api_docker_image:
        type: string
        required: true
      cli_docker_image:
        type: string
        required: true
      ui_docker_image:
        type: string
        required: true
    outputs:
      api_url:
        value: ${{ jobs.deploy_paas.outputs.api_url }}

concurrency: deploy_dev
jobs:
  deploy_paas:
    name: Deploy to PAAS
    runs-on: ubuntu-latest

    outputs:
      api_url: ${{ steps.deploy.outputs.api_url }}

    environment:
      name: dev

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/workflows/actions/deploy-paas-environment
      id: deploy
      with:
        environment_name: dev
        api_docker_image: ${{ inputs.api_docker_image }}
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
        terraform_vars: dev.tfvars.json
        terraform_backend_vars: dev.backend.tfvars

  deploy_aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest

    environment:
      name: dev_aks

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/workflows/actions/deploy-aks-environment
      id: deploy
      with:
        environment_name: dev
        api_docker_image: ${{ inputs.api_docker_image }}
        cli_docker_image: ${{ inputs.cli_docker_image }}
        ui_docker_image: ${{ inputs.ui_docker_image }}
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

