name: Deploy dev environment

on:
  workflow_call:
    inputs:
      docker_image:
        type: string
        required: true

concurrency: deploy_dev
jobs:
  deploy_aks:
    name: Deploy to AKS
    runs-on: ubuntu-latest

    environment:
      name: dev_aks

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/actions/deploy-aks-environment
      id: deploy
      with:
        environment_name: dev
        docker_image: ${{ inputs.docker_image }}
        azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

